const sheets = [
  {id:"architecture",index:"01",icon:"⌘",accent:"#3b82f6",title:"Architecture des 7 VMs",summary:"Rôles, adressage WireGuard, flux, placement Oracle Cloud / VirtualBox et limites.",sections:[
    ["Cartographie","VM1 gateway/bastion ; VM2 application Docker/PostgreSQL ; VM3 Prometheus/Grafana/Alertmanager ; VM4 Wazuh/Suricata ; VM5 OpenLDAP ; VM6 AD/DNS/Kerberos/GPO ; VM7 poste Windows joint au domaine."],
    ["Réseau","Overlay WireGuard 10.8.0.0/24 en hub-and-spoke, VM1 comme hub, UDP 51820. Les routes /32 limitent les destinations annoncées. VM1 est exposée ; VM3 reste privée et s’administre par ProxyJump."],
    ["Hébergement","VM1 et VM3 sont prévues sur Oracle Cloud ; les cinq autres VMs sont locales sous VirtualBox. La maquette combine ainsi accès cloud, services locaux et identité hybride."],
    ["Flux à défendre","Administration : WireGuard puis bastion. Application : HTTPS vers Nginx puis réseaux Docker. Linux : LDAPS 636 vers VM5. Windows : DNS/Kerberos/LDAP vers VM6. Télémétrie : exporters vers VM3 et agents vers VM4."],
    ["Limites / production","VM1 est un SPOF. Il manque HA VPN, annuaires redondants, segmentation IT/OT et réseau administrable. Production : deux gateways, bascule, VLAN/VRF, NGFW et cluster de virtualisation."],
    ["RNCP","CP2 réseau, CP3 systèmes, CP4 virtualisation, CP5 conception et CP6 mise en production."]]},
  {id:"ebios",index:"02",icon:"◈",accent:"#f59e0b",title:"EBIOS Risk Manager",summary:"Valeurs métier, biens supports, événements redoutés, sources, scénarios et résiduels.",sections:[
    ["Définitions","Valeur métier : ce qui compte pour l’organisation. Bien support : composant qui la réalise. Événement redouté : dommage sur la valeur. Source de risque : acteur et objectif. Scénario : chemin crédible vers le dommage."],
    ["6 événements","Critiques : fuite industrielle, AD compromis, OpenLDAP compromis. Majeurs : indisponibilité prolongée, altération PostgreSQL. Modéré : effacement des journaux/perte de traçabilité."],
    ["4 sources","Cybercriminel/extorsion ; opportuniste/VM1 ; espionnage industriel/données ; employé malveillant ou négligent/abus ou phishing."],
    ["8 scénarios","Brute force gateway ; exploitation web ; phishing VM7 ; compte privilégié AD ; OpenLDAP compromis ; ransomware ; exfiltration ; effacement des traces."],
    ["Résiduels","Trois faibles : gateway, web, traces. Cinq modérés : phishing, AD, OpenLDAP, ransomware, exfiltration. Le facteur humain et l’industrialisation incomplète expliquent ce reste."],
    ["Réponse jury","Un risque modéré est connu, traité, documenté et accepté pour le lab. Production : MFA généralisé, CIS Windows, EDR, IPS inline, sauvegardes immuables et réévaluation."],
    ["RNCP","CP5, CP8 et CP9."]]},
  {id:"zerotrust",index:"03",icon:"◌",accent:"#a78bfa",title:"Zero Trust",summary:"Cinq principes traduits en contrôles concrets, sans présenter Zero Trust comme un produit.",sections:[
    ["Vérifier explicitement","Clés ED25519, TOTP sur VM1, OpenLDAP/SSSD, Kerberos/AD, groupes et journaux d’authentification."],
    ["Moindre privilège","RBAC par 8 groupes, comptes de service nologin, root SSH interdit, sudo limité, PostgreSQL non publié et compte de jointure dédié."],
    ["Micro-segmentation","WireGuard + nftables, réseaux Docker frontend/backend, VM3 privée, ouvertures minimales."],
    ["Supposer la compromission","Wazuh, FIM, auditd, Suricata, ClamAV, Fail2ban et Active Response."],
    ["Journaliser","Agents Wazuh, événements Windows, EVE JSON, auditd verrouillé et centralisation sur VM4."],
    ["Limite","MFA non généralisé, autorisation pas recalculée dynamiquement et segmentation surtout logicielle. Les principes sont appliqués, pas une maturité industrielle complète."],
    ["RNCP","CP1, CP2, CP3, CP8, CP9 et CP10."]]},
  {id:"identity",index:"04",icon:"◎",accent:"#38bdf8",title:"Identité hybride",summary:"OpenLDAP/SSSD pour Linux, AD/Kerberos/GPO pour Windows et gouvernance des droits.",sections:[
    ["OpenLDAP","dc=dataforge,dc=lab sur VM5. VM1/VM2/VM4 utilisent SSSD et LDAPS 636. ppolicy gère le verrouillage ; memberOf aide le RBAC."],
    ["Active Directory","dataforge.lab sur VM6 : DNS, Kerberos, GPO, audit et jointure VM7. Preuves : klist, gpresult, whoami /groups."],
    ["Modèle","19 utilisateurs, 5 comptes de service, 8 groupes et 8 OUs. Logique cohérente entre annuaires, sans synchronisation automatique démontrée."],
    ["Pourquoi deux","OpenLDAP est léger pour Linux ; AD fournit GPO/Kerberos aux postes. FreeIPA aurait mieux intégré Linux mais ajouté de la complexité."],
    ["Risques","Doublons, révocation incomplète, droits divergents, panne et compte privilégié compromis. AD peut diffuser des GPO ; LDAP peut ouvrir les hôtes SSSD."],
    ["Production","Source maîtresse, provisioning automatisé, Joiner-Mover-Leaver, recertification, MFA privilégié, deux DCs, réplication LDAP et coffre de secrets."],
    ["RNCP","CP1, CP3, CP5 et CP9."]]},
  {id:"hardening",index:"05",icon:"▣",accent:"#fb7185",title:"Sécurisation et code",summary:"SSH, nftables, Fail2ban, Docker, scripts, auditd, Lynis et périmètre PFE/DP.",sections:[
    ["SSH","ED25519, PermitRootLogin no dans DataForge, PasswordAuthentication no, MaxAuthTries 3, TOTP sur VM1. Avant reload : backup, seconde session et sshd -t."],
    ["Pare-feu","nftables DROP INPUT/FORWARD, established/related, loopback et flux nécessaires. Fail2ban réagit dynamiquement mais ne remplace pas le firewall."],
    ["Docker","Frontend/backend, PostgreSQL sans port public, Adminer limité, no-new-privileges, healthchecks, rotation. Production : non-root, secrets, seccomp/capabilities, scan d’images."],
    ["Audit","Lynis VM1 70, VM2 72, VM4 72, VM5 71 : indices, pas pourcentages. auditd : 9 règles ; -e 2 verrouille jusqu’au reboot."],
    ["Code backup","pg_dump dans df-postgres, gzip, date et purge après 30 jours. À ajouter : pipefail, contrôle du code retour, permissions, chiffrement, espace, hors site et restauration."],
    ["Périmètre","ModSecurity/OWASP CRS 4.25.0, CrowdSec 1.7.7 et 13 jails appartiennent à NetStrategy. DataForge : 4 jails VM1 et Suricata IDS."],
    ["DICAP","Disponibilité, Intégrité, Confidentialité, Auditabilité, Pérennité."],
    ["RNCP","CP1, CP3, CP6, CP8 et CP9."]]},
  {id:"soc",index:"06",icon:"⌁",accent:"#4ade80",title:"SOC / SIEM",summary:"Collecte, corrélation, détection, réponse et limites de visibilité.",sections:[
    ["Wazuh","4.7.5 all-in-one sur VM4 : Manager 1514/1515, API 55000, Indexer 9200, Dashboard. 7 actifs = manager local + 6 distants."],
    ["Détection","500+ règles natives, 7 custom 100001–100007, FIM, Vulnerability Detector, auditd et événements Windows. Test avec wazuh-logtest."],
    ["Suricata","6.0.4, ET Open, EVE JSON vers Wazuh. IDS et non IPS inline ; blocage via nftables, Fail2ban ou Active Response."],
    ["Windows","4624 succès ; 4625 échec ; 4768 TGT Kerberos ; 4719 politique d’audit. Toujours corréler compte, source et contexte."],
    ["RETEX","5 incidents testés : brute force, Nmap, compte backdoor, escalade www-data, handshakes WireGuard. 100 % vaut uniquement pour ce périmètre."],
    ["Limites","Sans TAP/mirroring, Suricata ne voit que le trafic présenté à VM4. Wazuh all-in-one demande dimensionnement et HA en production."],
    ["RNCP","CP8, CP9 et CP10."]]},
  {id:"monitoring",index:"07",icon:"◒",accent:"#22d3ee",title:"Supervision",summary:"Prometheus, exporters, Grafana, Alertmanager et Blackbox.",sections:[
    ["Collecte","Prometheus en pull. node_exporter sur 5 Linux ; windows_exporter sur VM6/VM7. Preuve : 7 Targets UP sur 10.8.0.x."],
    ["Grafana","CPU, RAM, disque, réseau, disponibilité et tendances. Un dashboard ne remplace pas une alerte ni un runbook."],
    ["Alertmanager","Groupe, déduplique, route, inhibe et notifie par mail/webhook."],
    ["Blackbox","Sondes HTTP/TCP/TLS : mesure le service perçu même si la VM et le processus sont encore UP."],
    ["Complémentarité","Prometheus = métriques santé/performance ; Wazuh = événements sécurité/traçabilité."],
    ["Production","SLI/SLO, seuils, runbooks, escalade, rétention, HA, sauvegarde et revue du bruit."],
    ["RNCP","CP1, CP6 et surtout CP7."]]},
  {id:"pca",index:"08",icon:"↻",accent:"#fb923c",title:"PCA / PRA",summary:"Objectifs, sauvegardes, rétention, restauration et stratégie 3-2-1.",sections:[
    ["Objectifs","RTO < 4 h ; RPO < 24 h ; MTTR < 2 h."],
    ["PostgreSQL","pg_dump quotidien 02 h, local VM2 + réplication cloud, 30 jours ; restauration psql/pg_restore."],
    ["OpenLDAP","slapcat LDIF quotidien, 30 jours, copie cloud ; restauration slapd arrêté avec propriétaires/permissions corrects."],
    ["AD","Windows Server Backup System State + LDIFDE, volume dédié, 14 jours. LDIFDE seul ne restaure pas tout le DC."],
    ["VM1 / logs","Configs WireGuard/Nginx/SSH/Fail2ban/nftables dans Git privé ; logs Wazuh 90 jours."],
    ["Validation","Restaurer isolé, contrôler code retour, objets, données et fonction, mesurer le temps. Fichier créé ≠ reprise prouvée."],
    ["Limite","3-2-1 seulement approchée : hors site partiel et pas d’immutabilité/offline généralisée."],
    ["RNCP","CP1, CP3, CP5, CP6 et CP9."]]},
  {id:"choices",index:"09",icon:"◇",accent:"#818cf8",title:"Choix technologiques",summary:"Forces, faiblesses et alternatives contextualisées.",sections:[
    ["Réseau","WireGuard vs OpenVPN/IPsec ; nftables vs OPNsense/pfSense/NGFW. Choix légers et natifs pour le lab."],
    ["Sécurité","Wazuh open source multi-OS mais exige stockage/tuning ; Suricata performant mais limité à l’IDS. Alternatives : Security Onion, Zeek, Elastic, Splunk."],
    ["Supervision","Prometheus/Grafana cloud-native ; Zabbix/Centreon plus intégrés pour une approche classique."],
    ["Identité","OpenLDAP léger ; FreeIPA plus intégré Linux ; AD adapté à GPO/Kerberos ; Entra ID pertinent SaaS/cloud."],
    ["Plateforme","Docker reproductible ; PostgreSQL robuste. VirtualBox lab ; Proxmox/VMware pour cluster/HA."],
    ["Règle orale","Besoin → contrainte → solution → preuve → faiblesse → alternative. Jamais “meilleur” sans contexte."],
    ["RNCP","CP2 à CP8 selon le choix défendu."]]},
  {id:"professional",index:"10",icon:"▤",accent:"#c084fc",title:"Dossier professionnel",summary:"NetStrategy, résultats chiffrés, sécurité du changement et CP1–CP10.",sections:[
    ["Hardening","Ubuntu 24.04/Plesk : inventaire, 20 risques, 11 documents, SSH, Docker, swap, kernels, unattended-upgrades et Ubuntu Pro."],
    ["Résultats","Lynis 67→77→75 à 2 mois ; 266 Go libérés ; 9 conteneurs relancés ; 9 CVE kernel patchées à chaud."],
    ["Virtualisation","Lab Proxmox, 3 VMs Debian 12, réseau privé, OPNsense, supervision et automatisation : CP4/CP6/CP7."],
    ["Cybersécurité","ModSecurity CRS 4.25.0, detection-only puis blocage ; CrowdSec 1.7.7 ; 13 jails ; 7 ports Docker loopback ; incident LFI /.env."],
    ["Changement sûr","Seconde session, backup, sshd -t, reload contrôlé, tests, runbook, vérification de persistance."],
    ["Périmètre","Le DP analysé documente NetStrategy. Ne pas inventer une mission Alertis absente du dossier envoyé."],
    ["Méthode","Contexte → objectif → action personnelle → outils → résultat → difficulté → recul → CP."],
    ["RNCP","Preuves complémentaires sur les dix compétences, notamment production réelle, Proxmox, supervision, DevSecOps et incident."]]},
  {id:"traps",index:"11",icon:"!",accent:"#f43f5e",title:"Questions pièges",summary:"Limites, code, preuves, industrialisation et coût.",sections:[
    ["Architecture","Pourquoi aucun VLAN ? VM1 redondée ? Visibilité Suricata ? Wazuh all-in-one ? VirtualBox ?"],
    ["Identité","Deux annuaires ? Synchronisation ? Départ salarié ? FreeIPA ? MFA partout ?"],
    ["Code","pg_dump échoue avant gzip ? Secrets Docker ? Valider nftables/SSH ? auditd -e 2 ?"],
    ["Mesures","Lynis 72 = 72 % ? 7 agents distants ? Suricata bloque ? 100 % des attaques détectées ?"],
    ["Production","34 000 €/an ? Charge ? HA ? Sauvegarde immuable ? Changement et rollback ?"],
    ["Réponse type","Directe → justification → preuve → limite → amélioration. Si inconnu : dire comment vérifier."],
    ["RNCP","CP5, CP6, CP8, CP9 et CP10."]]},
  {id:"pitch",index:"12",icon:"▱",accent:"#0ea5e9",title:"Pitch oral 40 minutes",summary:"Fil, temps, transitions, preuves et posture.",sections:[
    ["0–5 min","Présentation, contexte industriel, problème, DICAP, besoin et rôle personnel."],
    ["5–13 min","7 VMs, cloud/local, WireGuard, flux et limites."],
    ["13–23 min","Zero Trust, hardening, Docker, identité hybride, RBAC, choix."],
    ["23–31 min","Prometheus/Grafana/Alertmanager, Wazuh/Suricata/auditd, incident."],
    ["31–36 min","EBIOS : valeurs, événements, sources, 8 scénarios, résiduels."],
    ["36–40 min","Tests, PCA/PRA, limites, industrialisation, coût, CP1–CP10, conclusion."],
    ["Posture","L’oral blanc a duré 25 min : ralentir, détailler forces/faiblesses, parler plus fort, varier l’intonation, supprimer “tac”."],
    ["Pages","Architecture pp.21–36 ; sécurité pp.37–42 ; supervision pp.43–45 ; SOC pp.46–54 ; IAM ch.10 ; PRA ch.11."]]}
];

const rawQcm = [
  ["Un administrateur distant doit intervenir sur VM2. Quel chemin respecte le mieux DataForge ?",["Internet → SSH direct VM2 → compte partagé","WireGuard vers VM1 → bastion authentifié → flux SSH explicitement autorisé vers VM2","Internet → PostgreSQL VM2 → authentification applicative","VPN VM1 → accès libre à tout le /24"],1,"Architecture","CP2 · CP3","Le tunnel ne suffit pas : VM1 centralise l’entrée, puis identité et nftables limitent le flux."],
  ["VM1 tombe alors que les six autres VMs restent actives. Quel diagnostic est exact ?",["Aucun impact : WireGuard devient maillé","Perte du hub VPN et du point d’entrée ; certains services locaux tournent mais accès inter-sites et administration sont affectés","Seule Grafana tombe","AD devient automatiquement gateway"],1,"Architecture","CP2 · CP5","VM1 est un SPOF reconnu ; la production exige redondance et bascule."],
  ["Pourquoi VM3 est-elle privée et atteinte via ProxyJump ?",["Prometheus ne supporte pas d’IP publique","Réduire l’exposition d’une console sensible tout en gardant un chemin contrôlé et traçable","Éviter WireGuard","Grafana remplace le firewall"],1,"Architecture","CP2 · CP7","La supervision révèle beaucoup sur le SI et mérite un accès indirect contrôlé."],
  ["Pourquoi utiliser des AllowedIPs /32 pour certains pairs WireGuard ?",["Désactiver le chiffrement","Limiter précisément les préfixes routés/annoncés par le pair","Attribuer une IP DHCP","Remplacer nftables"],1,"Réseau","CP2","AllowedIPs participe au routage et au contrôle des préfixes, sans remplacer le firewall."],
  ["Le jury critique VirtualBox. Quelle réponse est la plus mature ?",["VirtualBox est toujours meilleur","Il rend le lab portable ; Proxmox/VMware apporteraient cluster, HA, migration et administration centralisée en production","Proxmox ne gère pas Linux","La virtualisation n’impacte pas la disponibilité"],1,"Choix","CP4 · CP5","Le choix doit être relié au contexte et à la différence maquette/production."],
  ["Pourquoi l’absence de VLAN physiques n’annule-t-elle pas la segmentation ?",["Le VPN rend toute segmentation inutile","WireGuard, nftables et Docker démontrent le contrôle logiciel, mais ne remplacent pas VLAN/VRF/pare-feu IT-OT en production","VirtualBox certifie les VLAN","Suricata segmente"],1,"Réseau","CP2 · CP5","Il faut reconnaître le contrôle réel et sa limite industrielle."],
  ["Pourquoi ne pas publier PostgreSQL 5432 malgré un mot de passe robuste ?",["PostgreSQL ne route pas","Seul le backend en a besoin ; supprimer le chemin externe réduit surface et blast radius","Grafana l’interdit","Le mot de passe remplace le filtrage"],1,"Architecture","CP2 · CP3","La base reste derrière le backend et le réseau interne."],
  ["Le frontend Docker est compromis. Que limite le mouvement vers PostgreSQL ?",["Docker empêche toute compromission","Le backend et les flux nécessaires sont séparés ; la base n’est pas publiée","Docker chiffre toujours au repos","Le réseau remplace les comptes BDD"],1,"Conteneurs","CP3 · CP8","La segmentation limite le rayon, avec identités, secrets et durcissement en complément."],
  ["Le filtrage cloud autorise un flux que nftables bloque. Résultat ?",["Le cloud a priorité","Le flux reste bloqué : chaque couche du chemin doit l’autoriser","nftables se désactive","WireGuard contourne tout"],1,"Réseau","CP2 · CP3","Les contrôles cloud, hôte et applicatif sont cumulatifs."],
  ["Quel angle mort faut-il reconnaître pour Suricata sur VM4 ?",["Il voit tout automatiquement","Sans TAP/mirroring, il voit seulement le trafic présenté à VM4 ; le trafic chiffré inter-VM peut échapper","Il ne lit que Windows","ET Open déchiffre WireGuard"],1,"Architecture","CP2 · CP8","Placement de sonde et chiffrement déterminent la visibilité."],

  ["Laquelle est un événement redouté plutôt qu’un scénario ?",["847 essais SSH sur VM1","Fuite de données industrielles avec perte de confiance","Phishing VM7 puis mouvement latéral","Abus d’un groupe AD"],1,"EBIOS","CP8 · CP9","L’événement décrit le dommage ; le scénario décrit le chemin et l’acteur."],
  ["PostgreSQL est principalement quoi par rapport aux données industrielles ?",["Source de risque","Bien support","Mesure","Événement redouté"],1,"EBIOS","CP5 · CP8","La base supporte la valeur métier."],
  ["Quel ensemble restitue les six événements redoutés ?",["Fuite, AD, OpenLDAP, indisponibilité, altération PostgreSQL, perte de traçabilité","Phishing, Nmap, brute force, LFI, DDoS, malware","VM1 à VM6","Confidentialité, disponibilité, intégrité"],0,"EBIOS","CP8 · CP9","Trois critiques, deux majeurs, un modéré."],
  ["Répartition résiduelle des huit scénarios ?",["8 faibles","3 faibles et 5 modérés","5 faibles et 3 critiques","Aucun résiduel"],1,"EBIOS","CP8 · CP9","Identité, données et humain restent partiellement exposés."],
  ["Pourquoi cinq scénarios restent-ils modérés ?",["Aucune mesure","Facteur humain et contrôles non industrialisés : MFA généralisé, CIS complet, IPS inline","Wazuh l’impose","Modéré = accepté définitivement"],1,"EBIOS","CP8 · CP9","L’acceptation du lab reste accompagnée d’un plan de production."],
  ["Comment défendre l’acceptation de cinq risques modérés ?",["Ils sont gratuits","Acceptation bornée au lab, contrôles existants, limites documentées et axes d’industrialisation","Ils ne nécessitent jamais d’action","Grafana les supprimera"],1,"EBIOS","CP5 · CP9","Une décision de risque doit être formalisée et réévaluée."],
  ["Mesures contre l’exfiltration par espionnage ?",["VLAN et DLP SaaS uniquement","WireGuard, LDAPS/Kerberos, FIM, Suricata ET Open et SIEM","Mot de passe BDD seul","Backup seul"],1,"EBIOS","CP2 · CP8 · CP9","La chaîne couvre transport, identité, hôte, réseau et corrélation."],
  ["Pourquoi l’effacement des traces devient-il faible ?",["Logs cachés localement","Logs déportés, auditd -e 2 et FIM sur chemins sensibles","Aucun accès réseau","Prometheus garde toutes les commandes"],1,"EBIOS","CP8 · CP10","L’attaquant doit contourner plusieurs preuves, dont une plateforme distante."],
  ["Quelle mesure illustre “vérifier explicitement” ?",["Faire confiance au /24","Combiner identité, clé/TOTP, groupes et autorisation du flux","Autoriser tous les pairs","Mot de passe commun"],1,"Zero Trust","CP1 · CP3 · CP9","Un tunnel ne crée pas une confiance implicite."],
  ["Quelle combinaison traduit “supposer la compromission” ?",["Désactiver les logs","FIM, auditd, Wazuh, Suricata, ClamAV et procédures de réponse","Ouvrir les ports","Sauvegarder VM1 seulement"],1,"Zero Trust","CP8 · CP10","Il faut détecter, limiter et investiguer après un premier accès."],

  ["Pourquoi ne pas dire que LDAP et AD sont automatiquement synchronisés ?",["Deux annuaires ne partagent jamais rien","Le dossier prouve une logique cohérente, pas un moteur de synchro bidirectionnelle","Kerberos synchronise tout","SSSD copie vers AD"],1,"Identité","CP3 · CP5","Cohérence de conception et synchronisation déployée sont différentes."],
  ["Pratique conforme pour les 5 comptes de service ?",["Tous administrateurs","Shell nologin et droits du seul service","Compte partagé par les humains","sudo sans mot de passe"],1,"Identité","CP3 · CP9","Un compte technique est non interactif, limité et traçable."],
  ["getent résout un utilisateur mais la session Linux échoue. Analyse ?",["LDAP forcément HS","Résolution NSS OK ; vérifier PAM/SSSD, shell, home, groupes, règles d’accès et logs","Réinstaller AD","Ouvrir PostgreSQL"],1,"Identité","CP1 · CP3","Résolution et autorisation de session sont deux étapes."],
  ["Quel enchaînement valide l’authentification Windows de VM7 ?",["Ping VM6","DNS correct, jointure, klist, gpresult, whoami /groups","Compte local","Grafana accessible"],1,"Identité","CP3 · CP6","La preuve couvre domaine, Kerberos, politiques et groupes."],
  ["Réponse exacte sur le MFA DataForge ?",["Partout","TOTP sur VM1 ; généralisation privilégiée à faire en production","WireGuard est toujours MFA","Kerberos rend MFA inutile"],1,"Identité","CP3 · CP9","Ne pas généraliser une preuve locale."],
  ["ppolicy et memberOf sont complémentaires comment ?",["Chiffrement et backup","Mot de passe/verrouillage d’un côté ; appartenance groupes/RBAC de l’autre","Ils remplacent SSSD","Ils créent les GPO"],1,"Identité","CP3 · CP9","Authentification et autorisation sont distinctes."],
  ["Risque au départ d’un salarié ?",["Perte Prometheus","Révocation dans un annuaire mais compte encore actif dans l’autre","Suppression des backups","Arrêt WireGuard"],1,"Identité","CP1 · CP9","Joiner-Mover-Leaver doit garantir cohérence et preuve."],
  ["Pourquoi pas FreeIPA ?",["Il ne gère pas les comptes","OpenLDAP suffisait et restait léger ; FreeIPA apporte Kerberos/CA/politiques mais plus de complexité","Windows seulement","AD l’interdit"],1,"Choix","CP5","Une alternative peut être bonne mais disproportionnée pour le périmètre."],

  ["Procédure sûre avant reload sshd distant ?",["Fermer la session","Seconde session, backup, sshd -t, reload, nouvelle connexion de test","Reboot sans test","Activer Telnet"],1,"Code / exploitation","CP1 · CP6","Le DP documente cette sécurité du changement."],
  ["Pourquoi accepter established,related dans nftables ?",["Rendre tous les ports publics","Autoriser le retour des connexions déjà admises sans ouvrir de nouveaux flux","Désactiver l’état","Remplacer WireGuard"],1,"Code / réseau","CP2 · CP3","Le suivi d’état garde le refus par défaut cohérent."],
  ["Pourquoi garder nftables si Fail2ban a 4 jails ?",["nftables définit la surface en amont ; Fail2ban réagit après certains événements","Fail2ban désactive le firewall","nftables sert seulement aux logs","Ils sont identiques"],0,"Sécurisation","CP2 · CP9","Politique minimale statique et réponse dynamique sont complémentaires."],
  ["Risque de `pg_dump | gzip > dump.sql.gz` ?",["Aucun","Sans pipefail/contrôle, une archive invalide peut être créée après échec de pg_dump","Le fichier devient public","gzip restaure la base"],1,"Code / sauvegarde","CP1 · CP6","Contrôler pipeline, intégrité et code retour."],
  ["Que fait `find ... -mtime +30 -delete` ?",["Supprime les dumps de plus de 30 jours correspondant au motif","Chiffre les dumps","Restaure le dernier","Supprime PostgreSQL"],0,"Code / sauvegarde","CP1","C’est la rétention locale ; chemin et motif doivent être vérifiés."],
  ["Défaut d’un backup uniquement sur VM2 ?",["Aucun","Panne/compromission peut détruire production et copie ; il faut séparation et hors site","RTO devient nul","pg_dump exige le cloud"],1,"PCA / PRA","CP5 · CP6 · CP9","Une copie locale partage le domaine de panne."],
  ["Publication Docker réduisant la surface d’un outil local ?",["0.0.0.0:8080:8080","127.0.0.1:8080:8080 avec tunnel contrôlé","8080:22","network_mode host"],1,"Conteneurs","CP2 · CP3","Le loopback évite l’écoute sur toutes les interfaces."],
  ["Pratique sûre pour un secret PostgreSQL Compose ?",["Clair dans Git public","Gestionnaire de secrets ou fichier protégé non versionné, rotation et droits minimaux","Nom du conteneur","Même secret que root"],1,"Code / conteneurs","CP3 · CP9","La segmentation ne compense pas un secret exposé."],
  ["Lynis 72 signifie ?",["72 % d’attaques bloquées","Indice relatif aux contrôles testés, utile pour comparer et prioriser","72 CVE","Certification CIS"],1,"Audit","CP8","Lynis n’est ni pentest complet ni certification."],
  ["Effet de auditd `-e 2` ?",["Efface après 2 jours","Verrouille les règles jusqu’au redémarrage","Deux copies Wazuh","Désactive le noyau"],1,"Sécurisation","CP3 · CP8","Il complique la modification discrète des règles."],
  ["ModSecurity apparaît dans le DP. Bonne réponse ?",["Forcément sur VM2","Déployé chez NetStrategy ; ne pas le revendiquer dans DataForge sans preuve PFE","Identique à Suricata","Le DP ne sera pas questionné"],1,"DP / périmètre","CP8 · CP10","Toujours attribuer la preuve au bon contexte."],
  ["Pourquoi ModSecurity en detection-only avant blocage ?",["Empêcher les logs","Observer, qualifier les faux positifs et adapter avant production","Désactiver CRS","Remplacer les tests"],1,"DP / sécurité","CP6 · CP10","Le déploiement progressif réduit le risque métier."],
  ["DICAP exact ?",["Disponibilité, Intégrité, Confidentialité, Auditabilité, Pérennité","Détection, Investigation, Cloud, Active Response, Prometheus","Domaine, Identité, Conteneur, AD, PostgreSQL","Données, Internet, Cron, API, Proxy"],0,"Sécurisation","CP5 · CP9","DICAP structure sécurité et continuité."],
  ["`no-new-privileges:true` protège principalement contre ?",["Toute attaque réseau","Acquisition de nouveaux privilèges par le processus, notamment via setuid","Perte BDD","Phishing"],1,"Conteneurs","CP3 · CP8","À compléter par non-root, capabilities, seccomp et patching."],

  ["Sept agents Wazuh actifs signifie ?",["7 distants + manager","Manager local + 6 distants = 7 machines","5 Linux seulement","7 managers"],1,"SOC","CP7 · CP10","Ne pas surcompter l’architecture."],
  ["Association correcte des ports Wazuh ?",["1514 agents, 1515 enrôlement, 55000 API, 9200 Indexer","1514 Grafana, 1515 LDAP, 55000 WG, 9200 SSH","Tous PostgreSQL","Tous Suricata"],0,"SOC","CP3 · CP10","Connaître ces flux permet de défendre le pare-feu."],
  ["Valider une règle Wazuh custom comment ?",["Reboot sans test","wazuh-logtest sur événement représentatif, décodage, niveau et faux positifs","Modifier l’Indexer","Désactiver les natives"],1,"SOC","CP6 · CP10","Une règle doit être testée, versionnée et observée."],
  ["Suricata déclenche ET Open. Que se passe-t-il ?",["Blocage garanti","Alerte IDS ; blocage séparé via nftables, Fail2ban ou Active Response","Suppression automatique","WireGuard arrêté"],1,"SOC","CP8 · CP10","Le PFE insiste sur IDS, pas IPS inline."],
  ["Avantage de corréler Suricata, auditd et agents ?",["Zéro faux positif","Relier réseau, action système et identité pour qualifier","Remplacer backup","Chiffrer"],1,"SOC","CP8 · CP10","La corrélation enrichit le contexte."],
  ["Événement 4768 ?",["Demande de TGT Kerberos à analyser avec contexte","Politique d’audit modifiée","PostgreSQL arrêté","Nmap"],0,"SOC","CP3 · CP10","L’ID isolé n’est pas une conclusion."],
  ["Comment formuler 100 % de détection ?",["100 % de toutes les attaques","Les 5 incidents documentés ont été détectés ; aucune garantie universelle","Aucune compromission future","Suricata a tout bloqué"],1,"SOC","CP8 · CP10","Borner le résultat à l’échantillon testé."],
  ["FIM alerte sur /etc/passwd. Que prouve-t-il ?",["L’attaquant est identifié","Un changement ; corréler utilisateur, auditd, processus et changement attendu","Restauration finie","Fichier forcément malveillant"],1,"SOC","CP8 · CP10","FIM détecte l’intégrité, pas l’intention."],
  ["Pourquoi Prometheus est pull ?",["Exporters interrogent Grafana","Prometheus scrape les endpoints des exporters","Wazuh pousse dedans","Alertmanager collecte les paquets"],1,"Supervision","CP7","Le collecteur maîtrise fréquence et état des cibles."],
  ["Rôle exact d’Alertmanager ?",["Stocker métriques","Grouper, dédupliquer, inhiber, router et notifier","Analyser WireGuard","Appliquer GPO"],1,"Supervision","CP7","Prometheus évalue ; Alertmanager gère la notification."],
  ["Pourquoi Blackbox si node_exporter est UP ?",["Dupliquer CPU","Tester HTTP/TCP/TLS comme un client ; processus vivant ≠ service utilisable","Remplacer Grafana","Sauver AD"],1,"Supervision","CP7","Il mesure la disponibilité perçue."],
  ["CPU 5 % mais application en 500. Signal pertinent ?",["Probe HTTP Blackbox + logs applicatifs/Wazuh","Lynis seul","4719 seul","pg_dump"],0,"Supervision","CP7 · CP10","Croiser disponibilité applicative, logs et hôte."],

  ["Différence RTO/RPO/MTTR ?",["RTO perte, RPO temps, MTTR rétention","RTO indisponibilité visée, RPO perte de données, MTTR temps moyen de rétablissement","Identiques","RPO logs seulement"],1,"PCA / PRA","CP5 · CP6","DataForge vise <4 h, <24 h et <2 h."],
  ["Meilleure preuve d’un dump ?",["Fichier non vide","Restauration isolée, objets/données contrôlés, fonction testée et temps mesuré","Cron présent","VM2 UP"],1,"PCA / PRA","CP1 · CP6","La restauration prouve la valeur opérationnelle."],
  ["Pourquoi System State plutôt que LDIFDE seul ?",["LDIFDE contient l’OS","System State couvre les composants AD/système ; LDIFDE complète les objets","C’est un dashboard","Ne jamais sauver AD"],1,"PCA / PRA","CP3 · CP6","La méthode dépend du scénario de panne."],
  ["Pourquoi 3-2-1 seulement approchée ?",["3 clouds","Hors site et immutabilité ne couvrent pas tout","PostgreSQL interdit 3 copies","Wazuh ne garde rien"],1,"PCA / PRA","CP5 · CP9","L’externalisation reste partielle."],
  ["Comment défendre 34 000 €/an ?",["Prix fixe universel","Estimation avec hypothèses cloud/matériel, support, backup, logs, exploitation et humain, présentée en fourchette","Coût VirtualBox","Wazuh uniquement"],1,"Industrialisation","CP5 · CP6","Un coût isolé sans hypothèses n’est pas défendable."],
  ["Meilleur lot d’industrialisation ?",["Thème Grafana","HA gateway/annuaires, MFA, IT-OT, backups immuables, EDR/IPS, automatisation/versioning","Plus de ports","Supprimer logs"],1,"Industrialisation","CP5 · CP6 · CP9","Ces mesures ciblent les risques résiduels structurants."],

  ["Pourquoi seconde session SSH et sshd -t démontrent CP6 ?",["Saisie plus rapide","Préparation, validation et possibilité de retour","Remplacent la doc","Empêchent les CVE"],1,"DP / RNCP","CP6","CP6 porte la maîtrise du changement."],
  ["Résultat DP prouvant une amélioration durable ?",["Beaucoup d’outils","Lynis 67→77 puis 75 à 2 mois, écarts expliqués","Plesk présent","11 fichiers seuls"],1,"DP / RNCP","CP1 · CP8","Mesure initiale, action, mesure finale et persistance."],
  ["Remédiation des 7 ports Docker publics NetStrategy ?",["Bind 0.0.0.0 vers 127.0.0.1 dans Compose puis test externe","Mot de passe commun","Supprimer proxy","Ouvrir un 8e"],0,"DP / code","CP2 · CP3 · CP9","Le loopback réduit la surface."],
  ["Traitement complet de la LFI `/.env` ?",["Ignorer","Détecter, qualifier, WAF bloquant, règle Nginx 15 domaines, déplacer backup, documenter, vérifier à 2 mois","Supprimer logs","Reboot BDD"],1,"DP / incident","CP9 · CP10","Détection, qualification, remédiation, capitalisation et contrôle."],
  ["Que manque-t-il surtout à CP4 dans DataForge ?",["Capture VM7","Cluster, HA, stockage partagé/distribué, migration et exploitation","Règle Wazuh","Groupe LDAP"],1,"Référentiel","CP4","Le DP Proxmox apporte une preuve complémentaire."],
  ["Qu’est-ce qui renforce CP6 au-delà du déploiement ?",["Dire que ça marche","Plan, prérequis, backup, tests, supervision, doc, rollback et transfert","Couleurs slides","Installer sans valider"],1,"Référentiel","CP6","La mise en production est un processus."],
  ["Pourquoi Lynis/Nmap/Nikto/Wazuh/tests relèvent de CP8 ?",["Ils mesurent plusieurs aspects et produisent des écarts priorisables","Ils gèrent GPO","Ils remplacent EBIOS","Ils gèrent la paie"],0,"Référentiel","CP8","CP8 demande mesure, analyse et recommandations."],
  ["Comportement démontrant le mieux CP10 ?",["Réciter les outils","Détection, qualification, priorité, confinement, éradication, restauration, preuve, communication et RETEX","Wazuh fait tout","Éviter les faux positifs"],1,"Référentiel","CP10","Le jury évalue la chaîne et le jugement."]
];

const categoryMap = {
  "Architecture":"Architecture & réseau", "Réseau":"Architecture & réseau", "Choix":"Architecture & réseau",
  "Conteneurs":"Sécurisation & code", "Code / exploitation":"Sécurisation & code", "Code / réseau":"Sécurisation & code",
  "Sécurisation":"Sécurisation & code", "Code / sauvegarde":"Sécurisation & code", "Code / conteneurs":"Sécurisation & code", "Audit":"Sécurisation & code",
  "EBIOS":"EBIOS & Zero Trust", "Zero Trust":"EBIOS & Zero Trust", "Identité":"Identité hybride",
  "SOC":"SOC / SIEM", "Supervision":"Supervision", "PCA / PRA":"PCA / PRA",
  "DP / périmètre":"Dossier professionnel", "DP / sécurité":"Dossier professionnel", "DP / RNCP":"Dossier professionnel",
  "DP / code":"Dossier professionnel", "DP / incident":"Dossier professionnel",
  "Industrialisation":"Production & RNCP", "Référentiel":"Production & RNCP"
};
const qcm = rawQcm.map((item,index)=>({id:index+1,q:item[0],options:item[1],answer:item[2],category:categoryMap[item[3]]||item[3],competency:item[4],explanation:item[5]}));

const flashcards = [
  ["7 VMs ?","VM1 gateway ; VM2 Docker/BDD ; VM3 supervision ; VM4 SOC ; VM5 LDAP ; VM6 AD ; VM7 poste Windows."],
  ["WireGuard ?","10.8.0.0/24, UDP 51820, VM1 hub."],
  ["Cloud/local ?","VM1 et VM3 Oracle ; cinq autres VirtualBox."],
  ["SPOF ?","VM1, hub VPN et point d’entrée."],
  ["ProxyJump VM3 ?","Garder la supervision privée via VM1."],
  ["Pourquoi /32 ?","Limiter les préfixes routés/annoncés."],
  ["Pas de VLAN ?","Pas de switch L2/L3 ; WireGuard/nftables/Docker dans le lab, VLAN/VRF en prod."],
  ["VirtualBox ?","Portable pour lab ; Proxmox/VMware pour HA/cluster."],
  ["6 événements ?","Fuite, AD, LDAP, indisponibilité, altération BDD, perte de traces."],
  ["3 critiques ?","Fuite, AD compromis, LDAP compromis."],
  ["4 sources ?","Cybercriminel, opportuniste, espionnage, employé."],
  ["8 scénarios ?","Gateway, web, phishing, AD, LDAP, ransomware, exfiltration, traces."],
  ["Résiduels ?","3 faibles, 5 modérés."],
  ["5 principes Zero Trust ?","Vérifier, moindre privilège, micro-segmenter, supposer compromis, journaliser."],
  ["OpenLDAP ?","dc=dataforge,dc=lab sur VM5."],
  ["AD ?","dataforge.lab sur VM6."],
  ["IAM chiffres ?","19 utilisateurs, 5 services, 8 groupes, 8 OUs."],
  ["SSSD ?","Intègre identité/groupes LDAP à NSS/PAM Linux."],
  ["Kerberos ?","Authentification Windows par tickets ; TGT avec klist."],
  ["ppolicy/memberOf ?","Politique mot de passe/verrouillage ; appartenance groupes."],
  ["Risque double annuaire ?","Divergence et révocation incomplète."],
  ["MFA réel ?","TOTP VM1, pas généralisé."],
  ["SSH ?","ED25519, root non, mot de passe non, MaxAuthTries 3, TOTP."],
  ["Changement SSH sûr ?","Seconde session, backup, sshd -t, reload, test."],
  ["nftables ?","DROP INPUT/FORWARD, established/related, ouvertures minimales."],
  ["Fail2ban DataForge ?","4 jails VM1."],
  ["Fail2ban NetStrategy ?","13 jails : ne pas confondre."],
  ["Docker ?","Frontend/backend, PostgreSQL non publié."],
  ["Risque pg_dump|gzip ?","Archive invalide si pg_dump échoue sans pipefail/contrôle."],
  ["Lynis DataForge ?","70, 72, 72, 71."],
  ["Lynis 72 ?","Indice, pas 72 % de sécurité."],
  ["DICAP ?","Disponibilité, Intégrité, Confidentialité, Auditabilité, Pérennité."],
  ["auditd ?","9 règles, -e 2 verrouillé."],
  ["Wazuh ?","4.7.5 ; manager local + 6 distants."],
  ["Ports Wazuh ?","1514, 1515, 55000, 9200."],
  ["Règles custom ?","7 : 100001–100007, test wazuh-logtest."],
  ["Suricata ?","6.0.4 IDS, ET Open, EVE JSON, pas IPS."],
  ["Angle mort Suricata ?","Pas tout le trafic sans TAP/mirroring, surtout chiffré."],
  ["Windows IDs ?","4624 succès, 4625 échec, 4768 TGT, 4719 audit."],
  ["FIM ?","Changement d’intégrité à qualifier."],
  ["5 incidents ?","Brute force, Nmap, backdoor, www-data, handshakes WG."],
  ["100 % ?","Les 5 tests seulement."],
  ["Prometheus ?","Pull/scrape."],
  ["Exporters ?","5 node_exporter, VM6/7 windows_exporter."],
  ["Alertmanager ?","Groupe, déduplique, inhibe, route, notifie."],
  ["Blackbox ?","HTTP/TCP/TLS perçu par client."],
  ["Prometheus/Wazuh ?","Métriques vs sécurité/logs."],
  ["RTO/RPO/MTTR ?","<4 h / <24 h / <2 h."],
  ["Preuve backup ?","Restauration isolée, intégrité, fonction, temps."],
  ["LDAP backup ?","slapcat LDIF quotidien, 30 jours."],
  ["AD backup ?","System State + LDIFDE, 14 jours."],
  ["3-2-1 ?","Approchée, hors site/immutabilité à renforcer."],
  ["ModSecurity ?","NetStrategy DP, pas DataForge sans preuve."],
  ["NetStrategy chiffres ?","Lynis 67→77→75, 266 Go, 9 conteneurs, 9 CVE."],
  ["Incident .env ?","LFI détectée, bloquée, backup déplacé, 15 domaines, runbook, contrôle 2 mois."],
  ["Méthode jury ?","Direct → justification → preuve → limite → amélioration."],
  ["CP4 limite ?","Pas cluster/HA/stockage partagé DataForge ; DP Proxmox complète."],
  ["CP6 ?","Plan, backup, changement, tests, monitoring, doc, rollback."],
  ["34 000 € ?","Estimation à défendre par hypothèses et fourchette."],
  ["Durée ?","40 minutes, en français selon le centre."],
  ["Oral blanc ?","Ralentir, détailler forces/faiblesses, voix, intonation, supprimer “tac”."],
  ["Si je ne sais pas ?","Ne pas inventer ; borner, vérifier, proposer prudemment."]
];

const oralQuestions = [
  ["Architecture","Présentez DataForge et votre rôle en 90 secondes.","Entreprise industrielle fictive de 120 personnes sur trois sites. J’ai conçu et déployé une maquette de sept VMs pour sécuriser accès, identités, données et exploitation. Deux VMs sont prévues sur Oracle Cloud, cinq sous VirtualBox, reliées par WireGuard. L’identité est hybride OpenLDAP/AD et la défense combine durcissement, supervision, SIEM et PRA. Je distingue la cible de production des preuves du lab."],
  ["Architecture","Expliquez un flux administrateur vers VM2.","WireGuard vers VM1, identité et TOTP au bastion, puis flux SSH explicitement autorisé par nftables vers VM2. VM2 n’est pas exposée. Les authentifications et actions remontent à Wazuh."],
  ["Architecture","Que se passe-t-il si VM1 tombe ?","Perte du hub et du point d’entrée. Certains services locaux peuvent tourner, mais les accès inter-sites et l’administration sont coupés. Production : deux gateways, bascule, synchronisation et tests."],
  ["Réseau","Pourquoi pas de VLAN physiques ?","Pas de switch administrable dans le lab. WireGuard, nftables et Docker démontrent la segmentation. Production : VLAN/VRF, NGFW, inter-zones et séparation IT/OT."],
  ["Choix","Pourquoi VirtualBox ?","Portable et reproductible pour le lab. Proxmox/VMware en production pour cluster, HA, migration, stockage et administration. Mon DP apporte Proxmox."],
  ["Zero Trust","Prouvez les 5 principes.","Clés/TOTP/LDAP/Kerberos ; RBAC/nologin ; WireGuard/nftables/Docker ; FIM/auditd/Suricata ; Wazuh/logs. Limites : MFA et autorisation dynamique non généralisés."],
  ["EBIOS","Valeur, support, événement, scénario ?","Valeur : donnée/continuité. Support : PostgreSQL/AD/LDAP. Événement : fuite ou annuaire compromis. Scénario : chemin, par exemple phishing VM7 vers VM6."],
  ["EBIOS","Pourquoi 3 critiques ?","Fuite affecte confiance/conformité ; AD donne contrôle Windows/GPO ; LDAP ouvre les hôtes SSSD. Impacts systémiques."],
  ["EBIOS","Pourquoi accepter 5 modérés ?","Acceptation bornée au lab après traitement. Facteur humain et contrôles non industrialisés. Production : responsable, plan, échéance, MFA, CIS, EDR, IPS et réévaluation."],
  ["Identité","Pourquoi 2 annuaires ?","LDAP léger pour Linux/SSSD ; AD pour DNS/Kerberos/GPO Windows. FreeIPA plus intégré mais plus complexe. Contrepartie : gouvernance de deux sources."],
  ["Identité","Sont-ils synchronisés ?","Je ne revendique pas de synchronisation automatique. Production : source maîtresse, provisioning, Joiner-Mover-Leaver, recertification."],
  ["Identité","Pourquoi MFA pas partout ?","Priorité au bastion VM1. Limite assumée. Production : MFA privilégié, accès distants, consoles critiques et récupération contrôlée."],
  ["SSH","Changer SSH sans couper l’accès ?","Seconde session, backup, sshd -t, reload, nouvelle connexion, logs, fermeture ensuite. Méthode prouvée dans le DP."],
  ["Code","Expliquez et critiquez le backup PostgreSQL.","pg_dump dans df-postgres, gzip, date, purge 30 jours. Ajouter pipefail, code retour, intégrité, permissions, chiffrement, espace, hors site et test automatique de restauration."],
  ["Docker","BDD non exposée suffit ?","Non : comptes distincts, secrets, droits, patching, chiffrement backups, réseau backend, non-root, capabilities/seccomp et logs."],
  ["Audit","Lynis 72 = 72 % sécurisé ?","Non, indice relatif. À croiser avec Nmap, Nikto, vulnérabilités, Wazuh et tests."],
  ["SOC","Chaîne Suricata vers traitement ?","ET Open → EVE JSON → Wazuh → corrélation hôte/audit → qualification → confinement nftables/Fail2ban/Active Response. Suricata reste IDS."],
  ["SOC","100 % de détection crédible ?","Oui seulement pour les 5 incidents testés. Pas une couverture universelle ; mentionner faux négatifs, tuning et angle mort réseau."],
  ["SOC","7 agents Wazuh ?","Manager local VM4 + 6 distants = 7 machines couvertes."],
  ["SOC","Alerte FIM /etc/passwd ?","Corréler heure, utilisateur, processus, diff, auditd, sudo et changement. Si illégitime : contenir, préserver, restaurer, chercher persistance, RETEX."],
  ["Supervision","Prometheus et Wazuh doublon ?","Non : métriques santé/capacité contre événements sécurité/traçabilité. Grafana, Alertmanager et Blackbox complètent."],
  ["Supervision","VM UP, application KO ?","node_exporter peut rester UP. Probe Blackbox, healthcheck, métriques métier, logs application/Nginx/Docker/Wazuh."],
  ["PRA","Prouver RTO < 4 h ?","Exercice chronométré de reconstruction/restauration/validation. Scripts et docs rendent plausible ; test complet confirme."],
  ["PRA","Pourquoi fichier backup insuffisant ?","Peut être vide, corrompu, incomplet ou sans clé. Restaurer isolé, vérifier objets/données/fonction et mesurer."],
  ["Production","Défendre 34 000 €/an ?","Estimation : cloud/matériel, support, sauvegarde, logs, réseau, licences, maintenance, humain. Donner charge, CAPEX/OPEX et fourchette."],
  ["Production","5 priorités ?","HA VM1/annuaires ; IT/OT ; MFA/secrets ; backups immuables/testés ; automatisation/conformité/rollback ; puis EDR/IPS selon risque."],
  ["DP","Hardening NetStrategy chiffré ?","20 risques, 11 docs, SSH/Docker/swap/Livepatch. Lynis 67→77→75, 266 Go, 9 conteneurs, 9 CVE sans downtime."],
  ["DP","Incident /.env ?","Vraie LFI parmi 13 événements, secrets qualifiés, WAF bloquant, Nginx 15 domaines, backup déplacé, tests 403/404, runbook, contrôle 2 mois."],
  ["RNCP","CP1–CP10 au même niveau ?","Toutes représentées, profondeur variable. CP3/7/8/9/10 fortes. CP4/6 à défendre avec Proxmox DP et processus de changement/rollback."],
  ["Posture","Correction oral blanc ?","Base claire mais 25 min. Ralentir, détailler forces/faiblesses, pages/CP, parler plus fort, varier l’intonation, gestes sobres, pause au lieu de “tac”."]
];

window.DATAFORGE_CONTENT = { sheets, qcm, flashcards, oralQuestions };
