const sheets = [
  {id:"architecture",index:"01",icon:"⌘",accent:"#3b82f6",title:"Architecture des 7 VMs",summary:"Rôles, adressage WireGuard, flux, placement Oracle Cloud / VirtualBox et limites.",sections:[
    ["Cartographie","VM1 gateway/bastion ; VM2 application Docker/PostgreSQL ; VM3 Prometheus/Grafana/Alertmanager ; VM4 Wazuh/Suricata ; VM5 OpenLDAP ; VM6 AD/DNS/Kerberos/GPO ; VM7 poste Windows joint au domaine."],
    ["Réseau","Overlay WireGuard 10.8.0.0/24 en hub-and-spoke, VM1 comme hub, UDP 51820. Les routes /32 limitent les destinations annoncées. VM1 est exposée ; VM3 reste privée et s’administre par ProxyJump."],
    ["Hébergement","VM1 et VM3 sont prévues sur Oracle Cloud ; les cinq autres VMs sont locales sous VirtualBox. La maquette combine ainsi accès cloud, services locaux et identité hybride."],
    ["Flux à défendre","Administration : WireGuard puis bastion. Application : HTTPS vers Nginx puis réseaux Docker. Linux : LDAPS 636 vers VM5. Windows : DNS/Kerberos/LDAP vers VM6. Télémétrie : exporters vers VM3 et agents vers VM4."],
    ["Limites / production","VM1 est un SPOF. Il manque HA VPN, annuaires redondants, segmentation IT/OT et réseau administrable. Production : deux gateways, bascule, VLAN/VRF, NGFW et cluster de virtualisation."],
    ["RNCP","CP2 réseau, CP3 systèmes, CP4 virtualisation, CP5 conception et CP6 mise en production."]]},
  {id:"ebios",index:"02",icon:"◈",accent:"#f59e0b",title:"EBIOS Risk Manager",summary:"Valeurs métier, biens supports, événements redoutés, sources, scénarios et résiduels.",sections:[
    ["Définitions","Valeur métier : ce qui compte pour l’organisation. Bien support : composant qui la réalise. Événement redouté : dommage sur la valeur. Source de risque : acteur et objectif. Scénario : chemin crédible vers le dommage."],
    ["6 événements","Critiques : fuite industrielle, AD compromis, OpenLDAP compromis. Majeurs : indisponibilité prolongée, altération PostgreSQL. Modéré : effacement des journaux/perte de traçabilité."],
    ["4 sources","Cybercriminel/extorsion ; opportuniste/VM1 ; espionnage industriel/données ; employé malveillant ou négligent/abus ou phishing."],
    ["8 scénarios","Brute force gateway ; exploitation web ; phishing VM7 ; compte privilégié AD ; OpenLDAP compromis ; ransomware ; exfiltration ; effacement des traces."],
    ["Résiduels","Trois faibles : gateway, web, traces. Cinq modérés : phishing, AD, OpenLDAP, ransomware, exfiltration. Le facteur humain et l’industrialisation incomplète expliquent ce reste."],
    ["Réponse jury","Un risque modéré est connu, traité, documenté et accepté pour le lab. Production : MFA généralisé, CIS Windows, EDR, IPS inline, sauvegardes immuables et réévaluation."],
    ["RNCP","CP5, CP8 et CP9."]]},
  {id:"zerotrust",index:"03",icon:"◌",accent:"#a78bfa",title:"Zero Trust",summary:"Cinq principes traduits en contrôles concrets, sans présenter Zero Trust comme un produit.",sections:[
    ["Vérifier explicitement","Clés ED25519, TOTP sur VM1, OpenLDAP/SSSD, Kerberos/AD, groupes et journaux d’authentification."],
    ["Moindre privilège","RBAC par 8 groupes, comptes de service nologin, root SSH interdit, sudo limité, PostgreSQL non publié et compte de jointure dédié."],
    ["Micro-segmentation","WireGuard + nftables, réseaux Docker frontend/backend, VM3 privée, ouvertures minimales."],
    ["Supposer la compromission","Wazuh, FIM, auditd, Suricata, ClamAV, Fail2ban et Active Response."],
    ["Journaliser","Agents Wazuh, événements Windows, EVE JSON, auditd verrouillé et centralisation sur VM4."],
    ["Limite","MFA non généralisé, autorisation pas recalculée dynamiquement et segmentation surtout logicielle. Les principes sont appliqués, pas une maturité industrielle complète."],
    ["RNCP","CP1, CP2, CP3, CP8, CP9 et CP10."]]},
  {id:"identity",index:"04",icon:"◎",accent:"#38bdf8",title:"Identité hybride",summary:"OpenLDAP/SSSD pour Linux, AD/Kerberos/GPO pour Windows et gouvernance des droits.",sections:[
    ["OpenLDAP","dc=dataforge,dc=lab sur VM5. VM1/VM2/VM4 utilisent SSSD et LDAPS 636. ppolicy gère le verrouillage ; memberOf aide le RBAC."],
    ["Active Directory","dataforge.lab sur VM6 : DNS, Kerberos, GPO, audit et jointure VM7. Preuves : klist, gpresult, whoami /groups."],
    ["Modèle","19 utilisateurs, 5 comptes de service, 8 groupes et 8 OUs. Logique cohérente entre annuaires, sans synchronisation automatique démontrée."],
    ["Pourquoi deux","OpenLDAP est léger pour Linux ; AD fournit GPO/Kerberos aux postes. FreeIPA aurait mieux intégré Linux mais ajouté de la complexité."],
    ["Risques","Doublons, révocation incomplète, droits divergents, panne et compte privilégié compromis. AD peut diffuser des GPO ; LDAP peut ouvrir les hôtes SSSD."],
    ["Production","Source maîtresse, provisioning automatisé, Joiner-Mover-Leaver, recertification, MFA privilégié, deux DCs, réplication LDAP et coffre de secrets."],
    ["RNCP","CP1, CP3, CP5 et CP9."]]},
  {id:"hardening",index:"05",icon:"▣",accent:"#fb7185",title:"Sécurisation et code",summary:"SSH, nftables, Fail2ban, Docker, scripts, auditd, Lynis et périmètre PFE/DP.",sections:[
    ["SSH","ED25519, PermitRootLogin no dans DataForge, PasswordAuthentication no, MaxAuthTries 3, TOTP sur VM1. Avant reload : backup, seconde session et sshd -t."],
    ["Pare-feu","nftables DROP INPUT/FORWARD, established/related, loopback et flux nécessaires. Fail2ban réagit dynamiquement mais ne remplace pas le firewall."],
    ["Docker","Frontend/backend, PostgreSQL sans port public, Adminer limité, no-new-privileges, healthchecks, rotation. Production : non-root, secrets, seccomp/capabilities, scan d’images."],
    ["Audit","Lynis VM1 70, VM2 72, VM4 72, VM5 71 : indices, pas pourcentages. auditd : 9 règles ; -e 2 verrouille jusqu’au reboot."],
    ["Code backup","pg_dump dans df-postgres, gzip, date et purge après 30 jours. À ajouter : pipefail, contrôle du code retour, permissions, chiffrement, espace, hors site et restauration."],
    ["Périmètre","ModSecurity/OWASP CRS 4.25.0, CrowdSec 1.7.7 et 13 jails appartiennent à NetStrategy. DataForge : 4 jails VM1 et Suricata IDS."],
    ["DICAP","Disponibilité, Intégrité, Confidentialité, Auditabilité, Pérennité."],
    ["RNCP","CP1, CP3, CP6, CP8 et CP9."]]},
  {id:"soc",index:"06",icon:"⌁",accent:"#4ade80",title:"SOC / SIEM",summary:"Collecte, corrélation, détection, réponse et limites de visibilité.",sections:[
    ["Wazuh","4.7.5 all-in-one sur VM4 : Manager 1514/1515, API 55000, Indexer 9200, Dashboard. 7 actifs = manager local + 6 distants."],
    ["Détection","500+ règles natives, 7 custom 100001–100007, FIM, Vulnerability Detector, auditd et événements Windows. Test avec wazuh-logtest."],
    ["Suricata","6.0.4, ET Open, EVE JSON vers Wazuh. IDS et non IPS inline ; blocage via nftables, Fail2ban ou Active Response."],
    ["Windows","4624 succès ; 4625 échec ; 4768 TGT Kerberos ; 4719 politique d’audit. Toujours corréler compte, source et contexte."],
    ["RETEX","5 incidents testés : brute force, Nmap, compte backdoor, escalade www-data, handshakes WireGuard. 100 % vaut uniquement pour ce périmètre."],
    ["Limites","Sans TAP/mirroring, Suricata ne voit que le trafic présenté à VM4. Wazuh all-in-one demande dimensionnement et HA en production."],
    ["RNCP","CP8, CP9 et CP10."]]},
  {id:"monitoring",index:"07",icon:"◒",accent:"#22d3ee",title:"Supervision",summary:"Prometheus, exporters, Grafana, Alertmanager et Blackbox.",sections:[
    ["Collecte","Prometheus en pull. node_exporter sur 5 Linux ; windows_exporter sur VM6/VM7. Preuve : 7 Targets UP sur 10.8.0.x."],
    ["Grafana","CPU, RAM, disque, réseau, disponibilité et tendances. Un dashboard ne remplace pas une alerte ni un runbook."],
    ["Alertmanager","Groupe, déduplique, route, inhibe et notifie par mail/webhook."],
    ["Blackbox","Sondes HTTP/TCP/TLS : mesure le service perçu même si la VM et le processus sont encore UP."],
    ["Complémentarité","Prometheus = métriques santé/performance ; Wazuh = événements sécurité/traçabilité."],
    ["Production","SLI/SLO, seuils, runbooks, escalade, rétention, HA, sauvegarde et revue du bruit."],
    ["RNCP","CP1, CP6 et surtout CP7."]]},
  {id:"pca",index:"08",icon:"↻",accent:"#fb923c",title:"PCA / PRA",summary:"Objectifs, sauvegardes, rétention, restauration et stratégie 3-2-1.",sections:[
    ["Objectifs","RTO < 4 h ; RPO < 24 h ; MTTR < 2 h."],
    ["PostgreSQL","pg_dump quotidien 02 h, local VM2 + réplication cloud, 30 jours ; restauration psql/pg_restore."],
    ["OpenLDAP","slapcat LDIF quotidien, 30 jours, copie cloud ; restauration slapd arrêté avec propriétaires/permissions corrects."],
    ["AD","Windows Server Backup System State + LDIFDE, volume dédié, 14 jours. LDIFDE seul ne restaure pas tout le DC."],
    ["VM1 / logs","Configs WireGuard/Nginx/SSH/Fail2ban/nftables dans Git privé ; logs Wazuh 90 jours."],
    ["Validation","Restaurer isolé, contrôler code retour, objets, données et fonction, mesurer le temps. Fichier créé ≠ reprise prouvée."],
    ["Limite","3-2-1 seulement approchée : hors site partiel et pas d’immutabilité/offline généralisée."],
    ["RNCP","CP1, CP3, CP5, CP6 et CP9."]]},
  {id:"choices",index:"09",icon:"◇",accent:"#818cf8",title:"Choix technologiques",summary:"Forces, faiblesses et alternatives contextualisées.",sections:[
    ["Réseau","WireGuard vs OpenVPN/IPsec ; nftables vs OPNsense/pfSense/NGFW. Choix légers et natifs pour le lab."],
    ["Sécurité","Wazuh open source multi-OS mais exige stockage/tuning ; Suricata performant mais limité à l’IDS. Alternatives : Security Onion, Zeek, Elastic, Splunk."],
    ["Supervision","Prometheus/Grafana cloud-native ; Zabbix/Centreon plus intégrés pour une approche classique."],
    ["Identité","OpenLDAP léger ; FreeIPA plus intégré Linux ; AD adapté à GPO/Kerberos ; Entra ID pertinent SaaS/cloud."],
    ["Plateforme","Docker reproductible ; PostgreSQL robuste. VirtualBox lab ; Proxmox/VMware pour cluster/HA."],
    ["Règle orale","Besoin → contrainte → solution → preuve → faiblesse → alternative. Jamais “meilleur” sans contexte."],
    ["RNCP","CP2 à CP8 selon le choix défendu."]]},
  {id:"professional",index:"10",icon:"▤",accent:"#c084fc",title:"Dossier professionnel",summary:"NetStrategy, résultats chiffrés, sécurité du changement et CP1–CP10.",sections:[
    ["Hardening","Ubuntu 24.04/Plesk : inventaire, 20 risques, 11 documents, SSH, Docker, swap, kernels, unattended-upgrades et Ubuntu Pro."],
    ["Résultats","Lynis 67→77→75 à 2 mois ; 266 Go libérés ; 9 conteneurs relancés ; 9 CVE kernel patchées à chaud."],
    ["Virtualisation","Lab Proxmox, 3 VMs Debian 12, réseau privé, OPNsense, supervision et automatisation : CP4/CP6/CP7."],
    ["Cybersécurité","ModSecurity CRS 4.25.0, detection-only puis blocage ; CrowdSec 1.7.7 ; 13 jails ; 7 ports Docker loopback ; incident LFI /.env."],
    ["Changement sûr","Seconde session, backup, sshd -t, reload contrôlé, tests, runbook, vérification de persistance."],
    ["Périmètre","Le DP analysé documente NetStrategy. Ne pas inventer une mission Alertis absente du dossier envoyé."],
    ["Méthode","Contexte → objectif → action personnelle → outils → résultat → difficulté → recul → CP."],
    ["RNCP","Preuves complémentaires sur les dix compétences, notamment production réelle, Proxmox, supervision, DevSecOps et incident."]]},
  {id:"traps",index:"11",icon:"!",accent:"#f43f5e",title:"Questions pièges",summary:"Limites, code, preuves, industrialisation et coût.",sections:[
    ["Architecture","Pourquoi aucun VLAN ? VM1 redondée ? Visibilité Suricata ? Wazuh all-in-one ? VirtualBox ?"],
    ["Identité","Deux annuaires ? Synchronisation ? Départ salarié ? FreeIPA ? MFA partout ?"],
    ["Code","pg_dump échoue avant gzip ? Secrets Docker ? Valider nftables/SSH ? auditd -e 2 ?"],
    ["Mesures","Lynis 72 = 72 % ? 7 agents distants ? Suricata bloque ? 100 % des attaques détectées ?"],
    ["Production","34 000 €/an ? Charge ? HA ? Sauvegarde immuable ? Changement et rollback ?"],
    ["Réponse type","Directe → justification → preuve → limite → amélioration. Si inconnu : dire comment vérifier."],
    ["RNCP","CP5, CP6, CP8, CP9 et CP10."]]},
  {id:"pitch",index:"12",icon:"▱",accent:"#0ea5e9",title:"Pitch oral 40 minutes",summary:"Fil, temps, transitions, preuves et posture.",sections:[
    ["0–5 min","Présentation, contexte industriel, problème, DICAP, besoin et rôle personnel."],
    ["5–13 min","7 VMs, cloud/local, WireGuard, flux et limites."],
    ["13–23 min","Zero Trust, hardening, Docker, identité hybride, RBAC, choix."],
    ["23–31 min","Prometheus/Grafana/Alertmanager, Wazuh/Suricata/auditd, incident."],
    ["31–36 min","EBIOS : valeurs, événements, sources, 8 scénarios, résiduels."],
    ["36–40 min","Tests, PCA/PRA, limites, industrialisation, coût, CP1–CP10, conclusion."],
    ["Posture","L’oral blanc a duré 25 min : ralentir, détailler forces/faiblesses, parler plus fort, varier l’intonation, supprimer “tac”."],
    ["Pages","Architecture pp.21–36 ; sécurité pp.37–42 ; supervision pp.43–45 ; SOC pp.46–54 ; IAM ch.10 ; PRA ch.11."]]}
];

const rawQcm = [
  ["Un administrateur distant doit intervenir sur VM2. Quel chemin respecte le mieux DataForge ?",["Internet → SSH direct VM2 → compte partagé","WireGuard vers VM1 → bastion authentifié → flux SSH explicitement autorisé vers VM2","Internet → PostgreSQL VM2 → authentification applicative","VPN VM1 → accès libre à tout le /24"],1,"Architecture","CP2 · CP3","Le tunnel ne suffit pas : VM1 centralise l’entrée, puis identité et nftables limitent le flux."],
  ["VM1 tombe alors que les six autres VMs restent actives. Quel diagnostic est exact ?",["Aucun impact : WireGuard devient maillé","Perte du hub VPN et du point d’entrée ; certains services locaux tournent mais accès inter-sites et administration sont affectés","Seule Grafana tombe","AD devient automatiquement gateway"],1,"Architecture","CP2 · CP5","VM1 est un SPOF reconnu ; la production exige redondance et bascule."],
  ["Pourquoi VM3 est-elle privée et atteinte via ProxyJump ?",["Prometheus ne supporte pas d’IP publique","Réduire l’exposition d’une console sensible tout en gardant un chemin contrôlé et traçable","Éviter WireGuard","Grafana remplace le firewall"],1,"Architecture","CP2 · CP7","La supervision révèle beaucoup sur le SI et mérite un accès indirect contrôlé."],
  ["Pourquoi utiliser des AllowedIPs /32 pour certains pairs WireGuard ?",["Désactiver le chiffrement","Limiter précisément les préfixes routés/annoncés par le pair","Attribuer une IP DHCP","Remplacer nftables"],1,"Réseau","CP2","AllowedIPs participe au routage et au contrôle des préfixes, sans remplacer le firewall."],
  ["Le jury critique VirtualBox. Quelle réponse est la plus mature ?",["VirtualBox est toujours meilleur","Il rend le lab portable ; Proxmox/VMware apporteraient cluster, HA, migration et administration centralisée en production","Proxmox ne gère pas Linux","La virtualisation n’impacte pas la disponibilité"],1,"Choix","CP4 · CP5","Le choix doit être relié au contexte et à la différence maquette/production."],
  ["Pourquoi l’absence de VLAN physiques n’annule-t-elle pas la segmentation ?",["Le VPN rend toute segmentation inutile","WireGuard, nftables et Docker démontrent le contrôle logiciel, mais ne remplacent pas VLAN/VRF/pare-feu IT-OT en production","VirtualBox certifie les VLAN","Suricata segmente"],1,"Réseau","CP2 · CP5","Il faut reconnaître le contrôle réel et sa limite industrielle."],
  ["Pourquoi ne pas publier PostgreSQL 5432 malgré un mot de passe robuste ?",["PostgreSQL ne route pas","Seul le backend en a besoin ; supprimer le chemin externe réduit surface et blast radius","Grafana l’interdit","Le mot de passe remplace le filtrage"],1,"Architecture","CP2 · CP3","La base reste derrière le backend et le réseau interne."],
  ["Le frontend Docker est compromis. Que limite le mouvement vers PostgreSQL ?",["Docker empêche toute compromission","Le backend et les flux nécessaires sont séparés ; la base n’est pas publiée","Docker chiffre toujours au repos","Le réseau remplace les comptes BDD"],1,"Conteneurs","CP3 · CP8","La segmentation limite le rayon, avec identités, secrets et durcissement en complément."],
  ["Le filtrage cloud autorise un flux que nftables bloque. Résultat ?",["Le cloud a priorité","Le flux reste bloqué : chaque couche du chemin doit l’autoriser","nftables se désactive","WireGuard contourne tout"],1,"Réseau","CP2 · CP3","Les contrôles cloud, hôte et applicatif sont cumulatifs."],
  ["Quel angle mort faut-il reconnaître pour Suricata sur VM4 ?",["Il voit tout automatiquement","Sans TAP/mirroring, il voit seulement le trafic présenté à VM4 ; le trafic chiffré inter-VM peut échapper","Il ne lit que Windows","ET Open déchiffre WireGuard"],1,"Architecture","CP2 · CP8","Placement de sonde et chiffrement déterminent la visibilité."],

  ["Laquelle est un événement redouté plutôt qu’un scénario ?",["847 essais SSH sur VM1","Fuite de données industrielles avec perte de confiance","Phishing VM7 puis mouvement latéral","Abus d’un groupe AD"],1,"EBIOS","CP8 · CP9","L’événement décrit le dommage ; le scénario décrit le chemin et l’acteur."],
  ["PostgreSQL est principalement quoi par rapport aux données industrielles ?",["Source de risque","Bien support","Mesure","Événement redouté"],1,"EBIOS","CP5 · CP8","La base supporte la valeur métier."],
  ["Quel ensemble restitue les six événements redoutés ?",["Fuite, AD, OpenLDAP, indisponibilité, altération PostgreSQL, perte de traçabilité","Phishing, Nmap, brute force, LFI, DDoS, malware","VM1 à VM6","Confidentialité, disponibilité, intégrité"],0,"EBIOS","CP8 · CP9","Trois critiques, deux majeurs, un modéré."],
  ["Répartition résiduelle des huit scénarios ?",["8 faibles","3 faibles et 5 modérés","5 faibles et 3 critiques","Aucun résiduel"],1,"EBIOS","CP8 · CP9","Identité, données et humain restent partiellement exposés."],
  ["Pourquoi cinq scénarios restent-ils modérés ?",["Aucune mesure","Facteur humain et contrôles non industrialisés : MFA généralisé, CIS complet, IPS inline","Wazuh l’impose","Modéré = accepté définitivement"],1,"EBIOS","CP8 · CP9","L’acceptation du lab reste accompagnée d’un plan de production."],
  ["Comment défendre l’acceptation de cinq risques modérés ?",["Ils sont gratuits","Acceptation bornée au lab, contrôles existants, limites documentées et axes d’industrialisation","Ils ne nécessitent jamais d’action","Grafana les supprimera"],1,"EBIOS","CP5 · CP9","Une décision de risque doit être formalisée et réévaluée."],
  ["Mesures contre l’exfiltration par espionnage ?",["VLAN et DLP SaaS uniquement","WireGuard, LDAPS/Kerberos, FIM, Suricata ET Open et SIEM","Mot de passe BDD seul","Backup seul"],1,"EBIOS","CP2 · CP8 · CP9","La chaîne couvre transport, identité, hôte, réseau et corrélation."],
  ["Pourquoi l’effacement des traces devient-il faible ?",["Logs cachés localement","Logs déportés, auditd -e 2 et FIM sur chemins sensibles","Aucun accès réseau","Prometheus garde toutes les commandes"],1,"EBIOS","CP8 · CP10","L’attaquant doit contourner plusieurs preuves, dont une plateforme distante."],
  ["Quelle mesure illustre “vérifier explicitement” ?",["Faire confiance au /24","Combiner identité, clé/TOTP, groupes et autorisation du flux","Autoriser tous les pairs","Mot de passe commun"],1,"Zero Trust","CP1 · CP3 · CP9","Un tunnel ne crée pas une confiance implicite."],
  ["Quelle combinaison traduit “supposer la compromission” ?",["Désactiver les logs","FIM, auditd, Wazuh, Suricata, ClamAV et procédures de réponse","Ouvrir les ports","Sauvegarder VM1 seulement"],1,"Zero Trust","CP8 · CP10","Il faut détecter, limiter et investiguer après un premier accès."],

  ["Pourquoi ne pas dire que LDAP et AD sont automatiquement synchronisés ?",["Deux annuaires ne partagent jamais rien","Le dossier prouve une logique cohérente, pas un moteur de synchro bidirectionnelle","Kerberos synchronise tout","SSSD copie vers AD"],1,"Identité","CP3 · CP5","Cohérence de conception et synchronisation déployée sont différentes."],
  ["Pratique conforme pour les 5 comptes de service ?",["Tous administrateurs","Shell nologin et droits du seul service","Compte partagé par les humains","sudo sans mot de passe"],1,"Identité","CP3 · CP9","Un compte technique est non interactif, limité et traçable."],
  ["getent résout un utilisateur mais la session Linux échoue. Analyse ?",["LDAP forcément HS","Résolution NSS OK ; vérifier PAM/SSSD, shell, home, groupes, règles d’accès et logs","Réinstaller AD","Ouvrir PostgreSQL"],1,"Identité","CP1 · CP3","Résolution et autorisation de session sont deux étapes."],
  ["Quel enchaînement valide l’authentification Windows de VM7 ?",["Ping VM6","DNS correct, jointure, klist, gpresult, whoami /groups","Compte local","Grafana accessible"],1,"Identité","CP3 · CP6","La preuve couvre domaine, Kerberos, politiques et groupes."],
  ["Réponse exacte sur le MFA DataForge ?",["Partout","TOTP sur VM1 ; généralisation privilégiée à faire en production","WireGuard est toujours MFA","Kerberos rend MFA inutile"],1,"Identité","CP3 · CP9","Ne pas généraliser une preuve locale."],
  ["ppolicy et memberOf sont complémentaires comment ?",["Chiffrement et backup","Mot de passe/verrouillage d’un côté ; appartenance groupes/RBAC de l’autre","Ils remplacent SSSD","Ils créent les GPO"],1,"Identité","CP3 · CP9","Authentification et autorisation sont distinctes."],
  ["Risque au départ d’un salarié ?",["Perte Prometheus","Révocation dans un annuaire mais compte encore actif dans l’autre","Suppression des backups","Arrêt WireGuard"],1,"Identité","CP1 · CP9","Joiner-Mover-Leaver doit garantir cohérence et preuve."],
  ["Pourquoi pas FreeIPA ?",["Il ne gère pas les comptes","OpenLDAP suffisait et restait léger ; FreeIPA apporte Kerberos/CA/politiques mais plus de complexité","Windows seulement","AD l’interdit"],1,"Choix","CP5","Une alternative peut être bonne mais disproportionnée pour le périmètre."],

  ["Procédure sûre avant reload sshd distant ?",["Fermer la session","Seconde session, backup, sshd -t, reload, nouvelle connexion de test","Reboot sans test","Activer Telnet"],1,"Code / exploitation","CP1 · CP6","Le DP documente cette sécurité du changement."],
  ["Pourquoi accepter established,related dans nftables ?",["Rendre tous les ports publics","Autoriser le retour des connexions déjà admises sans ouvrir de nouveaux flux","Désactiver l’état","Remplacer WireGuard"],1,"Code / réseau","CP2 · CP3","Le suivi d’état garde le refus par défaut cohérent."],
  ["Pourquoi garder nftables si Fail2ban a 4 jails ?",["nftables définit la surface en amont ; Fail2ban réagit après certains événements","Fail2ban désactive le firewall","nftables sert seulement aux logs","Ils sont identiques"],0,"Sécurisation","CP2 · CP9","Politique minimale statique et réponse dynamique sont complémentaires."],
  ["Risque de `pg_dump | gzip > dump.sql.gz` ?",["Aucun","Sans pipefail/contrôle, une archive invalide peut être créée après échec de pg_dump","Le fichier devient public","gzip restaure la base"],1,"Code / sauvegarde","CP1 · CP6","Contrôler pipeline, intégrité et code retour."],
  ["Que fait `find ... -mtime +30 -delete` ?",["Supprime les dumps de plus de 30 jours correspondant au motif","Chiffre les dumps","Restaure le dernier","Supprime PostgreSQL"],0,"Code / sauvegarde","CP1","C’est la rétention locale ; chemin et motif doivent être vérifiés."],
  ["Défaut d’un backup uniquement sur VM2 ?",["Aucun","Panne/compromission peut détruire production et copie ; il faut séparation et hors site","RTO devient nul","pg_dump exige le cloud"],1,"PCA / PRA","CP5 · CP6 · CP9","Une copie locale partage le domaine de panne."],
  ["Publication Docker réduisant la surface d’un outil local ?",["0.0.0.0:8080:8080","127.0.0.1:8080:8080 avec tunnel contrôlé","8080:22","network_mode host"],1,"Conteneurs","CP2 · CP3","Le loopback évite l’écoute sur toutes les interfaces."],
  ["Pratique sûre pour un secret PostgreSQL Compose ?",["Clair dans Git public","Gestionnaire de secrets ou fichier protégé non versionné, rotation et droits minimaux","Nom du conteneur","Même secret que root"],1,"Code / conteneurs","CP3 · CP9","La segmentation ne compense pas un secret exposé."],
  ["Lynis 72 signifie ?",["72 % d’attaques bloquées","Indice relatif aux contrôles testés, utile pour comparer et prioriser","72 CVE","Certification CIS"],1,"Audit","CP8","Lynis n’est ni pentest complet ni certification."],
  ["Effet de auditd `-e 2` ?",["Efface après 2 jours","Verrouille les règles jusqu’au redémarrage","Deux copies Wazuh","Désactive le noyau"],1,"Sécurisation","CP3 · CP8","Il complique la modification discrète des règles."],
  ["ModSecurity apparaît dans le DP. Bonne réponse ?",["Forcément sur VM2","Déployé chez NetStrategy ; ne pas le revendiquer dans DataForge sans preuve PFE","Identique à Suricata","Le DP ne sera pas questionné"],1,"DP / périmètre","CP8 · CP10","Toujours attribuer la preuve au bon contexte."],
  ["Pourquoi ModSecurity en detection-only avant blocage ?",["Empêcher les logs","Observer, qualifier les faux positifs et adapter avant production","Désactiver CRS","Remplacer les tests"],1,"DP / sécurité","CP6 · CP10","Le déploiement progressif réduit le risque métier."],
  ["DICAP exact ?",["Disponibilité, Intégrité, Confidentialité, Auditabilité, Pérennité","Détection, Investigation, Cloud, Active Response, Prometheus","Domaine, Identité, Conteneur, AD, PostgreSQL","Données, Internet, Cron, API, Proxy"],0,"Sécurisation","CP5 · CP9","DICAP structure sécurité et continuité."],
  ["`no-new-privileges:true` protège principalement contre ?",["Toute attaque réseau","Acquisition de nouveaux privilèges par le processus, notamment via setuid","Perte BDD","Phishing"],1,"Conteneurs","CP3 · CP8","À compléter par non-root, capabilities, seccomp et patching."],

  ["Sept agents Wazuh actifs signifie ?",["7 distants + manager","Manager local + 6 distants = 7 machines","5 Linux seulement","7 managers"],1,"SOC","CP7 · CP10","Ne pas surcompter l’architecture."],
  ["Association correcte des ports Wazuh ?",["1514 agents, 1515 enrôlement, 55000 API, 9200 Indexer","1514 Grafana, 1515 LDAP, 55000 WG, 9200 SSH","Tous PostgreSQL","Tous Suricata"],0,"SOC","CP3 · CP10","Connaître ces flux permet de défendre le pare-feu."],
  ["Valider une règle Wazuh custom comment ?",["Reboot sans test","wazuh-logtest sur événement représentatif, décodage, niveau et faux positifs","Modifier l’Indexer","Désactiver les natives"],1,"SOC","CP6 · CP10","Une règle doit être testée, versionnée et observée."],
  ["Suricata déclenche ET Open. Que se passe-t-il ?",["Blocage garanti","Alerte IDS ; blocage séparé via nftables, Fail2ban ou Active Response","Suppression automatique","WireGuard arrêté"],1,"SOC","CP8 · CP10","Le PFE insiste sur IDS, pas IPS inline."],
  ["Avantage de corréler Suricata, auditd et agents ?",["Zéro faux positif","Relier réseau, action système et identité pour qualifier","Remplacer backup","Chiffrer"],1,"SOC","CP8 · CP10","La corrélation enrichit le contexte."],
  ["Événement 4768 ?",["Demande de TGT Kerberos à analyser avec contexte","Politique d’audit modifiée","PostgreSQL arrêté","Nmap"],0,"SOC","CP3 · CP10","L’ID isolé n’est pas une conclusion."],
  ["Comment formuler 100 % de détection ?",["100 % de toutes les attaques","Les 5 incidents documentés ont été détectés ; aucune garantie universelle","Aucune compromission future","Suricata a tout bloqué"],1,"SOC","CP8 · CP10","Borner le résultat à l’échantillon testé."],
  ["FIM alerte sur /etc/passwd. Que prouve-t-il ?",["L’attaquant est identifié","Un changement ; corréler utilisateur, auditd, processus et changement attendu","Restauration finie","Fichier forcément malveillant"],1,"SOC","CP8 · CP10","FIM détecte l’intégrité, pas l’intention."],
  ["Pourquoi Prometheus est pull ?",["Exporters interrogent Grafana","Prometheus scrape les endpoints des exporters","Wazuh pousse dedans","Alertmanager collecte les paquets"],1,"Supervision","CP7","Le collecteur maîtrise fréquence et état des cibles."],
  ["Rôle exact d’Alertmanager ?",["Stocker métriques","Grouper, dédupliquer, inhiber, router et notifier","Analyser WireGuard","Appliquer GPO"],1,"Supervision","CP7","Prometheus évalue ; Alertmanager gère la notification."],
  ["Pourquoi Blackbox si node_exporter est UP ?",["Dupliquer CPU","Tester HTTP/TCP/TLS comme un client ; processus vivant ≠ service utilisable","Remplacer Grafana","Sauver AD"],1,"Supervision","CP7","Il mesure la disponibilité perçue."],
  ["CPU 5 % mais application en 500. Signal pertinent ?",["Probe HTTP Blackbox + logs applicatifs/Wazuh","Lynis seul","4719 seul","pg_dump"],0,"Supervision","CP7 · CP10","Croiser disponibilité applicative, logs et hôte."],

  ["Différence RTO/RPO/MTTR ?",["RTO perte, RPO temps, MTTR rétention","RTO indisponibilité visée, RPO perte de données, MTTR temps moyen de rétablissement","Identiques","RPO logs seulement"],1,"PCA / PRA","CP5 · CP6","DataForge vise <4 h, <24 h et <2 h."],
  ["Meilleure preuve d’un dump ?",["Fichier non vide","Restauration isolée, objets/données contrôlés, fonction testée et temps mesuré","Cron présent","VM2 UP"],1,"PCA / PRA","CP1 · CP6","La restauration prouve la valeur opérationnelle."],
  ["Pourquoi System State plutôt que LDIFDE seul ?",["LDIFDE contient l’OS","System State couvre les composants AD/système ; LDIFDE complète les objets","C’est un dashboard","Ne jamais sauver AD"],1,"PCA / PRA","CP3 · CP6","La méthode dépend du scénario de panne."],
  ["Pourquoi 3-2-1 seulement approchée ?",["3 clouds","Hors site et immutabilité ne couvrent pas tout","PostgreSQL interdit 3 copies","Wazuh ne garde rien"],1,"PCA / PRA","CP5 · CP9","L’externalisation reste partielle."],
  ["Comment défendre 34 000 €/an ?",["Prix fixe universel","Estimation avec hypothèses cloud/matériel, support, backup, logs, exploitation et humain, présentée en fourchette","Coût VirtualBox","Wazuh uniquement"],1,"Industrialisation","CP5 · CP6","Un coût isolé sans hypothèses n’est pas défendable."],
  ["Meilleur lot d’industrialisation ?",["Thème Grafana","HA gateway/annuaires, MFA, IT-OT, backups immuables, EDR/IPS, automatisation/versioning","Plus de ports","Supprimer logs"],1,"Industrialisation","CP5 · CP6 · CP9","Ces mesures ciblent les risques résiduels structurants."],

  ["Pourquoi seconde session SSH et sshd -t démontrent CP6 ?",["Saisie plus rapide","Préparation, validation et possibilité de retour","Remplacent la doc","Empêchent les CVE"],1,"DP / RNCP","CP6","CP6 porte la maîtrise du changement."],
  ["Résultat DP prouvant une amélioration durable ?",["Beaucoup d’outils","Lynis 67→77 puis 75 à 2 mois, écarts expliqués","Plesk présent","11 fichiers seuls"],1,"DP / RNCP","CP1 · CP8","Mesure initiale, action, mesure finale et persistance."],
  ["Remédiation des 7 ports Docker publics NetStrategy ?",["Bind 0.0.0.0 vers 127.0.0.1 dans Compose puis test externe","Mot de passe commun","Supprimer proxy","Ouvrir un 8e"],0,"DP / code","CP2 · CP3 · CP9","Le loopback réduit la surface."],
  ["Traitement complet de la LFI `/.env` ?",["Ignorer","Détecter, qualifier, WAF bloquant, règle Nginx 15 domaines, déplacer backup, documenter, vérifier à 2 mois","Supprimer logs","Reboot BDD"],1,"DP / incident","CP9 · CP10","Détection, qualification, remédiation, capitalisation et contrôle."],
  ["Que manque-t-il surtout à CP4 dans DataForge ?",["Capture VM7","Cluster, HA, stockage partagé/distribué, migration et exploitation","Règle Wazuh","Groupe LDAP"],1,"Référentiel","CP4","Le DP Proxmox apporte une preuve complémentaire."],
  ["Qu’est-ce qui renforce CP6 au-delà du déploiement ?",["Dire que ça marche","Plan, prérequis, backup, tests, supervision, doc, rollback et transfert","Couleurs slides","Installer sans valider"],1,"Référentiel","CP6","La mise en production est un processus."],
  ["Pourquoi Lynis/Nmap/Nikto/Wazuh/tests relèvent de CP8 ?",["Ils mesurent plusieurs aspects et produisent des écarts priorisables","Ils gèrent GPO","Ils remplacent EBIOS","Ils gèrent la paie"],0,"Référentiel","CP8","CP8 demande mesure, analyse et recommandations."],
  ["Comportement démontrant le mieux CP10 ?",["Réciter les outils","Détection, qualification, priorité, confinement, éradication, restauration, preuve, communication et RETEX","Wazuh fait tout","Éviter les faux positifs"],1,"Référentiel","CP10","Le jury évalue la chaîne et le jugement."]
];

const categoryMap = {
  "Architecture":"Architecture & réseau", "Réseau":"Architecture & réseau", "Choix":"Architecture & réseau",
  "Conteneurs":"Sécurisation & code", "Code / exploitation":"Sécurisation & code", "Code / réseau":"Sécurisation & code",
  "Sécurisation":"Sécurisation & code", "Code / sauvegarde":"Sécurisation & code", "Code / conteneurs":"Sécurisation & code", "Audit":"Sécurisation & code",
  "EBIOS":"EBIOS & Zero Trust", "Zero Trust":"EBIOS & Zero Trust", "Identité":"Identité hybride",
  "SOC":"SOC / SIEM", "Supervision":"Supervision", "PCA / PRA":"PCA / PRA",
  "DP / périmètre":"Dossier professionnel", "DP / sécurité":"Dossier professionnel", "DP / RNCP":"Dossier professionnel",
  "DP / code":"Dossier professionnel", "DP / incident":"Dossier professionnel",
  "Industrialisation":"Production & RNCP", "Référentiel":"Production & RNCP"
};
const qcm = rawQcm.map((item,index)=>({id:index+1,q:item[0],options:item[1],answer:item[2],category:categoryMap[item[3]]||item[3],competency:item[4],explanation:item[5]}));

const flashcards = [
  ["Architecture", "Architecture des 7 VMs", "Quel est le rôle de chaque VM et pourquoi séparer ces fonctions ?",
   "Une architecture par rôles place chaque fonction importante sur un système distinct afin de limiter les dépendances, les privilèges et le rayon d'impact d'une compromission.",
   "Chaque VM expose uniquement les services nécessaires. Les flux entre rôles passent par WireGuard et sont filtrés. Cette séparation améliore la lisibilité, la supervision et la capacité à isoler un incident.",
   "VM1 est la gateway et le bastion ; VM2 héberge Docker, l'application et PostgreSQL ; VM3 supervise ; VM4 centralise le SOC ; VM5 fournit OpenLDAP ; VM6 fournit AD/DNS/Kerberos/GPO ; VM7 est le poste Windows joint au domaine.",
   "J'ai séparé les sept rôles pour appliquer le moindre privilège et éviter qu'un service applicatif compromis donne immédiatement accès aux annuaires ou au SIEM.",
   "Séparer en VMs ne crée pas automatiquement une haute disponibilité. Certaines VMs, notamment VM1 et les annuaires, restent des points uniques de défaillance dans la maquette."],

  ["Architecture", "WireGuard", "Qu'est-ce que WireGuard et comment structure-t-il le réseau DataForge ?",
   "WireGuard est un VPN de niveau 3 qui crée des interfaces réseau chiffrées entre des pairs identifiés par des clés publiques. Il transporte des paquets IP dans un tunnel UDP.",
   "Chaque pair possède une clé privée, connaît les clés publiques autorisées et associe des préfixes IP à ces pairs. Le chiffrement protège le trafic en transit ; le routage et le pare-feu décident ensuite quels services sont accessibles.",
   "Le réseau overlay est 10.8.0.0/24, le port d'écoute est UDP 51820 et VM1 joue le rôle de hub dans une topologie hub-and-spoke.",
   "WireGuard relie de manière chiffrée les VMs cloud et locales, mais je conserve nftables et les contrôles d'identité car un VPN ne constitue pas à lui seul une politique Zero Trust.",
   "WireGuard n'apporte ni gestion d'utilisateurs, ni MFA natif, ni filtrage applicatif. La chute du hub VM1 coupe une partie des communications inter-sites."],

  ["Architecture", "Architecture hybride cloud/local", "Pourquoi répartir DataForge entre Oracle Cloud et VirtualBox ?",
   "Une infrastructure hybride combine des ressources hébergées chez un fournisseur cloud avec des systèmes exécutés sur un site local. Elle permet de simuler des accès distants et des contraintes d'interconnexion réelles.",
   "Les deux environnements sont reliés par un réseau privé chiffré. Les services exposés ou utiles à distance peuvent être placés dans le cloud, tandis que les services internes restent dans le laboratoire local.",
   "VM1 et VM3 sont prévues sur Oracle Cloud ; VM2, VM4, VM5, VM6 et VM7 sont locales sous VirtualBox. WireGuard fournit la liaison 10.8.0.0/24.",
   "Ce placement me permet de démontrer une identité et une exploitation hybrides avec un point d'entrée cloud contrôlé et des services internes non directement exposés.",
   "La maquette ne reproduit pas la redondance, les SLA, le réseau industriel ni le dimensionnement d'une production de 120 personnes."],

  ["Architecture", "SPOF", "Qu'est-ce qu'un SPOF et lequel est le plus évident dans DataForge ?",
   "Un Single Point of Failure est un composant dont la panne suffit à rendre indisponible une fonction entière, faute de redondance ou de chemin alternatif.",
   "On l'identifie en étudiant les dépendances : si tous les flux ou toutes les authentifications passent par un seul composant, sa perte interrompt le service correspondant.",
   "VM1 est le SPOF principal : elle concentre le hub WireGuard, le bastion et le point d'entrée. VM5 et VM6 sont aussi seules pour leurs annuaires respectifs.",
   "La maquette assume VM1 comme point unique ; en production je déploierais deux gateways, une bascule testée et des annuaires répliqués.",
   "Dire que toutes les VMs continuent à tourner ne signifie pas que le service global reste disponible : les accès distants et inter-sites peuvent être coupés."],

  ["Architecture", "ProxyJump", "À quoi sert SSH ProxyJump pour administrer VM3 ?",
   "ProxyJump permet à un client SSH d'atteindre une machine privée en faisant transiter la connexion par un bastion intermédiaire, sans ouvrir directement la cible sur Internet.",
   "Le client établit d'abord une connexion au bastion puis crée un canal vers la cible. Les identités et autorisations de chaque étape restent distinctes et les flux doivent être autorisés par le pare-feu.",
   "VM3, qui contient Prometheus et Grafana, reste privée. L'administrateur rejoint d'abord VM1 puis atteint VM3 avec ProxyJump.",
   "J'ai protégé la supervision derrière le bastion car elle révèle la topologie, les noms d'hôtes et l'état de santé de toute l'infrastructure.",
   "ProxyJump réduit l'exposition mais rend l'administration dépendante du bastion. Il faut aussi journaliser, durcir et idéalement redonder ce bastion."],

  ["Réseau", "AllowedIPs en /32", "Pourquoi annoncer certaines adresses WireGuard en /32 ?",
   "Un préfixe /32 représente exactement une adresse IPv4. Dans WireGuard, AllowedIPs participe à la fois au choix du pair de sortie et à l'acceptation des adresses associées à ce pair.",
   "Une route plus précise évite d'annoncer tout un sous-réseau à un pair qui ne doit joindre qu'une machine. Cela réduit les erreurs de routage et les possibilités d'usurpation de préfixe.",
   "DataForge peut associer chaque pair à son adresse 10.8.0.x/32 plutôt que lui confier l'ensemble de 10.8.0.0/24.",
   "Les /32 rendent le routage des pairs plus précis ; je complète toujours ce contrôle par nftables pour limiter les ports et les sens de communication.",
   "AllowedIPs n'est pas un pare-feu applicatif : autoriser une IP ne doit pas donner accès à tous ses services."],

  ["Réseau", "Segmentation sans VLAN physique", "Comment défendre l'absence de VLAN physiques dans la maquette ?",
   "Un VLAN segmente logiquement un réseau de niveau 2 en domaines de diffusion séparés. La maquette ne dispose pas de commutateurs administrables permettant de démontrer cette segmentation physique de manière réaliste.",
   "La segmentation peut aussi être appliquée à d'autres niveaux : tunnels IP, filtrage L3/L4, réseaux virtuels Docker et contrôle des routes. Ces mécanismes limitent les flux mais ne remplacent pas tous les usages des VLAN.",
   "DataForge utilise WireGuard, nftables et deux réseaux Docker frontend/backend pour démontrer l'isolation logicielle.",
   "Je démontre une micro-segmentation logicielle dans le lab ; en production j'ajouterais VLAN ou VRF, pare-feu inter-zones et séparation stricte entre IT et OT.",
   "Ne pas prétendre que WireGuard est équivalent à un VLAN : ils n'agissent ni au même niveau, ni sur les mêmes menaces."],

  ["Virtualisation", "VirtualBox", "Pourquoi VirtualBox dans le PFE et quelles seraient les alternatives de production ?",
   "VirtualBox est un hyperviseur de type 2 exécuté au-dessus d'un système d'exploitation hôte. Il convient aux laboratoires grâce à sa simplicité, sa portabilité et son coût nul.",
   "Il crée des VMs avec CPU, mémoire, disque et interfaces virtuelles, mais n'offre pas nativement la même exploitation centralisée qu'un cluster de production.",
   "Cinq VMs DataForge sont exécutées localement sous VirtualBox. Le DP complète cette preuve avec un laboratoire Proxmox et trois VMs Debian provisionnées automatiquement.",
   "VirtualBox répond au besoin de maquette reproductible ; pour la production je choisirais Proxmox ou VMware selon le budget, le support, la HA, la migration et le stockage.",
   "Le choix d'un hyperviseur ne se défend pas par 'meilleur' : il dépend du SLA, des compétences, du support, de la sauvegarde et du coût."],

  ["EBIOS RM", "Événement redouté", "Qu'est-ce qu'un événement redouté et quels sont les six de DataForge ?",
   "Dans une analyse de risques, un événement redouté est une atteinte à une valeur métier entraînant un impact pour l'organisation. Il décrit le dommage, pas le chemin technique de l'attaque.",
   "On relie une valeur métier à un critère DICAP, à un impact et à une gravité. Les scénarios de menace expliquent ensuite comment cet événement pourrait se produire.",
   "Les six événements sont : fuite de données industrielles, compromission AD, compromission OpenLDAP, indisponibilité prolongée, altération PostgreSQL et perte de traçabilité par effacement des journaux.",
   "J'ai distingué les dommages métier des techniques d'attaque afin de prioriser les protections en fonction de leur impact sur DataForge.",
   "Un brute force, un phishing ou un ransomware sont des scénarios ou modes opératoires, pas des événements redoutés."],

  ["EBIOS RM", "Criticité des événements", "Pourquoi trois événements sont-ils classés critiques ?",
   "La criticité combine généralement la gravité de l'impact et la vraisemblance. Un événement critique menace durablement les opérations, la confidentialité ou le contrôle d'une grande partie du SI.",
   "La compromission d'un annuaire a un effet systémique : elle permet potentiellement l'usurpation d'identités, la modification des droits et le mouvement latéral.",
   "DataForge classe critiques la fuite industrielle, la compromission d'AD et celle d'OpenLDAP. AD contrôle l'écosystème Windows ; OpenLDAP ouvre l'accès aux hôtes Linux via SSSD.",
   "Ces trois événements dépassent la panne d'un service isolé car ils affectent les données sensibles ou la racine de confiance des utilisateurs.",
   "Critique ne veut pas dire certain. Il faut séparer la gravité métier de la probabilité technique."],

  ["EBIOS RM", "Source de risque", "Qu'est-ce qu'une source de risque et quelles sont celles retenues ?",
   "Une source de risque est un acteur susceptible de porter une menace, associé à un objectif visé. Elle peut être externe, interne, organisée, opportuniste ou involontaire.",
   "EBIOS RM cherche à comprendre qui attaque, pourquoi, avec quelles ressources et quels chemins plausibles. Cela évite de traiter toutes les menaces de manière identique.",
   "Les quatre sources retenues sont le cybercriminel cherchant l'extorsion, l'attaquant opportuniste ciblant l'exposition de VM1, l'espionnage industriel visant les données et l'employé malveillant ou négligent.",
   "J'ai relié chaque mesure à un acteur et à un objectif, par exemple la détection d'exfiltration face à l'espionnage industriel.",
   "Une vulnérabilité, un malware ou un serveur ne sont pas des sources de risque : ce sont respectivement une faiblesse, un moyen et un bien support."],

  ["EBIOS RM", "Scénario de menace", "Que décrivent les huit scénarios de DataForge ?",
   "Un scénario de menace décrit un chemin crédible depuis une source de risque jusqu'à un événement redouté, en passant par des biens supports et des actions techniques ou humaines.",
   "Il permet d'identifier les mesures préventives, détectives et correctives à chaque étape, puis d'évaluer le risque résiduel après traitement.",
   "Les huit scénarios portent sur le brute force de la gateway, l'exploitation web, le phishing de VM7, l'abus d'un compte AD, la compromission OpenLDAP, le ransomware, l'exfiltration et l'effacement des traces.",
   "Pour chaque scénario, j'ai associé une source, un chemin, un dommage, les mesures déployées et un niveau résiduel.",
   "Énumérer huit attaques ne suffit pas : il faut expliquer l'acteur, la cible, le chemin, l'impact et les contrôles."],

  ["EBIOS RM", "Risque résiduel", "Que signifie la répartition de trois risques faibles et cinq modérés ?",
   "Le risque résiduel est le niveau de risque qui subsiste après application des mesures de sécurité. Aucun dispositif raisonnable ne supprime totalement le risque.",
   "On réévalue gravité et vraisemblance en tenant compte des contrôles réellement prouvés. Le risque restant doit être accepté, transféré, évité ou encore réduit par un plan d'action.",
   "DataForge obtient trois scénarios faibles et cinq modérés. Les risques liés aux identités, aux données et au facteur humain restent modérés faute de MFA généralisé, d'EDR ou d'industrialisation complète.",
   "Les cinq risques modérés sont acceptés uniquement dans le périmètre du lab, avec des limites documentées et un plan de réduction pour la production.",
   "Modéré ne signifie ni négligeable ni accepté définitivement. Il faut un responsable, une échéance et une réévaluation."],

  ["Zero Trust", "Les cinq principes", "Comment expliquer Zero Trust sans le présenter comme un produit ?",
   "Zero Trust est un modèle de sécurité fondé sur l'absence de confiance implicite liée au réseau. Chaque accès doit être vérifié, limité et observé en fonction de l'identité, du contexte et de la ressource.",
   "Ses principes sont : vérifier explicitement, appliquer le moindre privilège, micro-segmenter, supposer la compromission et journaliser en continu.",
   "DataForge combine clés et TOTP, LDAP/Kerberos, groupes, nftables, réseaux Docker, Wazuh, FIM, auditd et Suricata pour traduire ces principes en contrôles concrets.",
   "Je n'ai pas installé un produit Zero Trust : j'ai appliqué ses cinq principes à l'identité, aux flux et à la détection.",
   "La maturité reste partielle : MFA non généralisé, autorisation peu dynamique et segmentation essentiellement logicielle."],

  ["Identité", "OpenLDAP", "Qu'est-ce qu'OpenLDAP et quel rôle joue-t-il dans DataForge ?",
   "OpenLDAP est une implémentation libre du protocole LDAP, utilisé pour stocker et interroger un annuaire hiérarchique d'objets comme les utilisateurs, groupes et unités d'organisation.",
   "Les entrées sont identifiées par un Distinguished Name. Les clients effectuent des recherches et des authentifications ; LDAPS protège les échanges par TLS.",
   "VM5 héberge la base dc=dataforge,dc=lab. Les hôtes Linux interrogent l'annuaire via SSSD et LDAPS 636 ; ppolicy et memberOf renforcent mots de passe et groupes.",
   "OpenLDAP centralise les identités Linux de DataForge avec un schéma léger et compatible SSSD.",
   "OpenLDAP seul n'apporte pas toutes les fonctions de FreeIPA ou AD : Kerberos intégré, GPO, CA et gouvernance complète doivent être ajoutés ou organisés."],

  ["Identité", "Active Directory", "Qu'est-ce qu'Active Directory au-delà d'un simple annuaire ?",
   "Active Directory Domain Services est un service d'annuaire Microsoft qui centralise identités, groupes, ordinateurs et politiques dans un domaine Windows.",
   "Il s'appuie fortement sur DNS pour localiser les services, Kerberos pour l'authentification et les GPO pour appliquer des configurations aux utilisateurs et machines.",
   "VM6 fournit le domaine dataforge.lab, DNS, Kerberos, les groupes et GPO. VM7 est jointe au domaine et peut être vérifiée avec klist, gpresult et whoami /groups.",
   "J'ai retenu AD pour le périmètre Windows car il fournit nativement la jointure de domaine, Kerberos et la gestion centralisée par GPO.",
   "Un seul contrôleur de domaine est un SPOF. En production il faut au moins deux DC, sauvegarde System State, durcissement des comptes privilégiés et réplication testée."],

  ["Identité", "Modèle IAM", "Que représentent les 19 utilisateurs, 5 comptes de service, 8 groupes et 8 OUs ?",
   "Un modèle IAM organise le cycle de vie des identités et sépare les personnes, les comptes techniques, les rôles et les unités administratives.",
   "Les groupes portent les autorisations ; les OUs structurent les objets et facilitent l'administration ou l'application de politiques. Les comptes de service doivent être non interactifs et limités.",
   "DataForge documente 19 utilisateurs, 5 comptes de service, 8 groupes de sécurité et 8 OUs avec une logique comparable entre LDAP et AD.",
   "J'attribue les droits aux groupes plutôt qu'aux personnes afin de rendre les accès lisibles, révocables et auditables.",
   "Avoir les mêmes noms dans deux annuaires ne prouve pas leur synchronisation. Il faut une source maîtresse et un processus Joiner-Mover-Leaver."],

  ["Identité", "SSSD", "Comment SSSD relie-t-il OpenLDAP aux machines Linux ?",
   "SSSD est un service Linux qui fournit l'accès aux identités et politiques provenant de sources distantes comme LDAP ou Active Directory.",
   "Il dialogue avec NSS pour résoudre utilisateurs et groupes, avec PAM pour l'authentification et peut mettre en cache certaines informations pour améliorer la résilience.",
   "VM1, VM2 et VM4 utilisent SSSD pour retrouver les comptes de dc=dataforge,dc=lab et contrôler l'accès Linux à partir des groupes LDAP.",
   "SSSD transforme l'annuaire LDAP en source d'identité utilisable par les mécanismes standard NSS et PAM de Linux.",
   "Si getent fonctionne mais que la connexion échoue, LDAP n'est pas forcément en panne : il faut vérifier PAM, le shell, le home, les groupes, les règles d'accès et les logs SSSD."],

  ["Identité", "Kerberos", "Comment fonctionne Kerberos et que prouve un TGT ?",
   "Kerberos est un protocole d'authentification par tickets. Il évite d'envoyer le mot de passe à chaque service et s'appuie sur un tiers de confiance appelé KDC.",
   "Après authentification, le client reçoit un Ticket Granting Ticket, puis demande des tickets de service. L'horloge et DNS doivent être corrects, sinon les échanges échouent.",
   "Dans dataforge.lab, VM6 joue le rôle de contrôleur de domaine et KDC. Sur VM7, klist permet de vérifier la présence et la durée des tickets.",
   "Kerberos prouve une authentification de domaine par tickets ; je complète la preuve avec la jointure, gpresult et les groupes de l'utilisateur.",
   "Un TGT ne prouve pas que toutes les autorisations sont correctes. Kerberos authentifie ; groupes, ACL et GPO autorisent et configurent."],

  ["Identité", "ppolicy et memberOf", "Pourquoi ces deux modules OpenLDAP sont-ils complémentaires ?",
   "ppolicy applique des règles relatives aux mots de passe, comme l'expiration ou le verrouillage. memberOf maintient ou expose l'appartenance d'un utilisateur à des groupes.",
   "Le premier agit surtout sur l'authentification et la robustesse des secrets ; le second facilite l'autorisation fondée sur les rôles.",
   "DataForge utilise ppolicy pour réduire le risque de mots de passe faibles ou d'essais répétés et memberOf pour exploiter les 8 groupes de sécurité avec SSSD.",
   "ppolicy protège l'accès au compte tandis que memberOf permet de décider ce que ce compte a le droit de faire.",
   "Ils ne chiffrent pas les échanges et ne remplacent ni LDAPS, ni la revue des droits, ni le cycle de vie des comptes."],

  ["Identité", "Risque du double annuaire", "Quel est le principal risque d'une identité hybride sans synchronisation ?",
   "Deux annuaires autonomes créent deux sources d'identité et donc un risque de divergence des comptes, groupes, mots de passe et révocations.",
   "Lors d'une arrivée, d'une mobilité ou d'un départ, l'opération doit être appliquée dans chaque système. Un oubli peut laisser un compte orphelin actif.",
   "OpenLDAP gère Linux et AD gère Windows avec des OUs cohérentes, mais le PFE ne prouve pas de synchronisation automatique bidirectionnelle.",
   "Le bénéfice fonctionnel des deux annuaires s'accompagne d'un risque de révocation incomplète que je traiterais par une source maîtresse et un provisioning automatisé.",
   "Ne jamais dire que SSSD ou Kerberos synchronisent les deux annuaires : ils assurent l'accès ou l'authentification, pas le provisioning global."],

  ["Identité", "MFA", "Qu'est-ce que le MFA et où est-il réellement appliqué ?",
   "L'authentification multifacteur exige au moins deux facteurs de catégories différentes : connaissance, possession ou caractéristique biométrique.",
   "Un mot de passe et un code TOTP constituent connaissance plus possession si la graine TOTP est conservée sur un second appareil. Deux mots de passe ne forment pas du MFA.",
   "DataForge démontre le TOTP sur le bastion VM1 en complément de la clé SSH. La généralisation aux annuaires et consoles n'est pas prouvée.",
   "J'ai priorisé le MFA sur le point d'entrée le plus exposé ; en production je l'étendrais aux comptes privilégiés, VPN, AD et consoles critiques.",
   "Une clé SSH seule est un facteur de possession, pas automatiquement du MFA. Il faut aussi prévoir récupération, révocation et synchronisation horaire."],

  ["Sécurisation", "Durcissement SSH", "Quels contrôles réduisent le risque sur SSH dans DataForge ?",
   "Le durcissement SSH réduit la surface d'attaque du service d'administration et limite l'impact d'un secret compromis.",
   "On désactive les chemins inutiles, impose une authentification forte, limite les essais, filtre les sources et journalise. La clé Ed25519 offre une authentification asymétrique moderne.",
   "DataForge utilise une clé Ed25519, PermitRootLogin no, PasswordAuthentication no, MaxAuthTries 3 et TOTP sur VM1, avec nftables et Fail2ban autour du service.",
   "J'ai supprimé l'accès root et le mot de passe SSH afin de réduire le brute force, puis ajouté TOTP sur le bastion exposé.",
   "Le durcissement peut provoquer un verrouillage administratif. Il faut tester la syntaxe, garder une seconde session et disposer d'un accès de secours maîtrisé."],

  ["Exploitation", "Changement SSH sûr", "Comment modifier SSH à distance sans se couper l'accès ?",
   "Un changement sûr prépare la validation et le retour arrière avant l'application. Le but est de limiter l'impact d'une erreur de configuration sur la disponibilité.",
   "On sauvegarde le fichier, garde une session ouverte, vérifie avec sshd -t, recharge sans redémarrage brutal, ouvre une nouvelle connexion de test puis contrôle les logs.",
   "Cette méthode est utilisée dans DataForge et surtout prouvée en production chez NetStrategy lors du hardening du serveur Plesk.",
   "Avant chaque reload SSH, je conserve une seconde session et je valide la configuration ; je ne ferme l'ancienne qu'après un test complet.",
   "Un simple backup ne suffit pas si personne ne peut se reconnecter pour le restaurer. Le rollback doit être accessible et chronométré."],

  ["Réseau", "nftables", "Quel est le rôle de nftables et que signifie DROP par défaut ?",
   "nftables est le framework moderne de filtrage de paquets du noyau Linux. Il permet de définir des tables, chaînes, règles et états de connexion.",
   "Une politique DROP refuse tout paquet qui ne correspond pas à une autorisation explicite. Les règles established,related laissent revenir les paquets des connexions déjà admises sans ouvrir de nouveaux flux.",
   "DataForge applique DROP sur INPUT et FORWARD, autorise loopback, established/related puis seulement WireGuard, SSH et les flux applicatifs ou de supervision nécessaires.",
   "Mon pare-feu part du refus et documente chaque exception par un besoin de flux ; cela réduit la surface exposée et facilite l'audit.",
   "Une mauvaise règle peut couper le VPN ou l'administration. Il faut valider, tester depuis une seconde session et prévoir un rollback."],

  ["Sécurisation", "Fail2ban dans DataForge", "Comment Fail2ban complète-t-il nftables ?",
   "Fail2ban analyse des journaux, reconnaît des échecs répétés à l'aide de filtres et applique temporairement une action de bannissement, souvent via le pare-feu.",
   "nftables définit la surface autorisée en permanence ; Fail2ban réagit dynamiquement au comportement d'une source après plusieurs événements.",
   "VM1 dispose de quatre jails adaptées aux services surveillés. Les bannissements et récidives peuvent être remontés vers Wazuh.",
   "Fail2ban ralentit le brute force et automatise une première réponse, mais il reste complémentaire de l'authentification forte et du filtrage réseau.",
   "Il peut bannir une adresse légitime, être contourné par une attaque distribuée et ne protège que ce qui produit des logs correctement analysés."],

  ["Dossier professionnel", "Fail2ban chez NetStrategy", "Pourquoi faut-il distinguer les 4 jails DataForge des 13 jails du DP ?",
   "Le PFE et le DP sont deux périmètres de preuve différents : DataForge est une maquette de formation, NetStrategy correspond aux missions professionnelles réelles documentées.",
   "Le jury peut croiser les dossiers. Une technologie présente dans l'un ne doit pas être attribuée à l'autre sans élément démontré.",
   "DataForge documente quatre jails sur VM1. Le serveur Plesk de NetStrategy en possède treize dans le cadre de sa défense en profondeur.",
   "Je précise toujours le contexte de la preuve : quatre jails dans DataForge, treize dans la mission NetStrategy du DP.",
   "Mélanger les chiffres fragilise la crédibilité, même si l'outil est le même."],

  ["Conteneurs", "Segmentation Docker", "Que protègent les réseaux frontend/backend et la non-publication de PostgreSQL ?",
   "Les réseaux Docker isolent logiquement les communications entre conteneurs. Publier un port crée un chemin depuis l'hôte ; ne pas le publier le réserve au réseau interne concerné.",
   "Le frontend communique avec le backend, et seul le backend doit joindre PostgreSQL. Cette architecture réduit les chemins disponibles si le frontend est compromis.",
   "VM2 sépare frontend et backend et n'expose pas PostgreSQL 5432 sur Internet. Des healthchecks et no-new-privileges complètent la configuration.",
   "La base n'est accessible que depuis le backend, ce qui réduit la surface d'attaque et le rayon d'impact d'une compromission du frontend.",
   "L'isolation réseau ne remplace pas les comptes BDD distincts, les secrets protégés, le mode non-root, seccomp, les capabilities minimales et le patching."],

  ["Sauvegarde", "Pipeline pg_dump et gzip", "Pourquoi pg_dump | gzip peut-il produire une fausse sauvegarde ?",
   "Un pipeline transmet la sortie d'une commande à la suivante. Par défaut, un shell peut retourner uniquement le statut de la dernière commande et masquer l'échec de la première.",
   "Si pg_dump échoue mais que gzip crée quand même un fichier vide ou incomplet, le cron peut sembler réussi. set -o pipefail, les codes retour, les logs et un contrôle d'intégrité rendent l'échec visible.",
   "Le script DataForge lance pg_dump depuis le conteneur PostgreSQL, compresse le résultat, le date et purge les archives de plus de trente jours.",
   "Je renforcerais le script avec pipefail, contrôle du code retour, permissions, chiffrement, espace disponible et test automatique de restauration.",
   "Un fichier présent et non vide n'est toujours pas une preuve de reprise : seule une restauration isolée valide la chaîne."],

  ["Audit", "Scores Lynis DataForge", "Quels sont les scores Lynis et à quoi servent-ils ?",
   "Lynis est un outil d'audit de sécurité et de durcissement pour systèmes Unix. Il examine de nombreux contrôles et produit des constats et recommandations.",
   "Son indice permet surtout de comparer un même système dans le temps et de prioriser des mesures. Il dépend du profil, de la version et des contrôles applicables.",
   "Les scores documentés sont VM1 70, VM2 72, VM4 72 et VM5 71.",
   "J'utilise Lynis comme indicateur de progression et je croise ses résultats avec Nmap, les configurations, Wazuh et les tests fonctionnels.",
   "Il ne faut pas transformer ces nombres en pourcentage de sécurité ni en certification CIS."],

  ["Audit", "Interprétation d'un score Lynis", "Pourquoi 72 ne signifie-t-il pas 72 % sécurisé ?",
   "La sécurité n'est pas une quantité totale mesurable par un seul nombre. Le score Lynis reflète les contrôles que l'outil a vérifiés et la pondération de son propre audit.",
   "Une machine peut obtenir un indice correct tout en conservant une vulnérabilité critique hors périmètre, une mauvaise logique métier ou un secret exposé.",
   "Dans DataForge, les scores servent à repérer des axes de hardening sur quatre VMs, puis à justifier des améliorations concrètes.",
   "Je présente Lynis comme un indice relatif d'audit, pas comme la probabilité qu'une attaque soit bloquée.",
   "Le jury peut volontairement demander '72 % ?' pour tester ta capacité à nuancer la métrique."],

  ["Sécurité", "DICAP", "Que signifie DICAP et comment l'utiliser dans un raisonnement de sécurité ?",
   "DICAP regroupe Disponibilité, Intégrité, Confidentialité, Auditabilité et Pérennité. Ces propriétés décrivent les besoins de sécurité et de continuité d'un système d'information.",
   "On identifie pour chaque valeur métier les propriétés nécessaires, puis les menaces, contrôles et preuves correspondants.",
   "WireGuard et LDAPS protègent la confidentialité ; FIM et sauvegardes contribuent à l'intégrité ; redondance et PRA à la disponibilité ; Wazuh à l'auditabilité ; formats ouverts et documentation à la pérennité.",
   "DICAP me permet de relier chaque choix technique à un besoin métier plutôt que d'additionner des outils.",
   "Un même contrôle peut contribuer à plusieurs propriétés, mais il faut expliquer précisément comment et avec quelle limite."],

  ["SOC", "auditd", "Quel est le rôle d'auditd et que fait -e 2 ?",
   "auditd collecte des événements d'audit du noyau Linux : accès à des fichiers sensibles, changements d'identité, exécutions ou modifications de configuration.",
   "Les règles définissent les objets et actions surveillés. Le paramètre -e 2 verrouille la configuration d'audit jusqu'au redémarrage, ce qui complique sa désactivation discrète par un attaquant.",
   "DataForge documente neuf règles auditd verrouillées et transmet leurs événements à Wazuh pour corrélation.",
   "auditd apporte une preuve système détaillée ; Wazuh la centralise et la rapproche des événements réseau et d'identité.",
   "Le verrouillage ne rend pas les logs inviolables et complique aussi un changement légitime. Les règles doivent être testées avant activation."],

  ["SOC", "Wazuh", "Qu'est-ce que Wazuh et quelles fonctions assure-t-il ?",
   "Wazuh est une plateforme open source de type SIEM/XDR combinant collecte d'agents, décodage, règles, intégrité des fichiers, vulnérabilités, recherche et réponse active.",
   "Les agents envoient leurs événements au manager ; les règles les qualifient ; l'Indexer les stocke et le Dashboard permet l'analyse. Des intégrations ajoutent Suricata, auditd ou Windows.",
   "VM4 héberge Wazuh 4.7.5 en all-in-one. Sept agents actifs signifient le manager local plus six machines distantes.",
   "Wazuh centralise les preuves de DataForge et corrèle les événements Linux, Windows, FIM, auditd et Suricata pour aider au traitement d'incident.",
   "Un SIEM ne détecte pas magiquement tout : la qualité dépend des sources, règles, horloges, rétention, tuning et procédures humaines."],

  ["SOC", "Ports Wazuh", "À quoi correspondent 1514, 1515, 55000 et 9200 ?",
   "Les ports représentent différents composants et phases de la chaîne Wazuh. Les connaître permet de concevoir un filtrage réseau minimal et de diagnostiquer un agent indisponible.",
   "1514 transporte les événements des agents, 1515 sert à leur enrôlement, 55000 expose l'API Wazuh et 9200 correspond à l'Indexer/OpenSearch.",
   "Dans DataForge, seuls les flux nécessaires sont ouverts entre les agents, VM4 et les postes d'administration autorisés.",
   "J'ai documenté chaque port par son besoin ; l'API et l'Indexer ne doivent pas être publiés librement sur Internet.",
   "Le protocole exact peut dépendre de la configuration. Une règle de pare-feu doit être vérifiée contre la configuration réellement déployée."],

  ["SOC", "Règles Wazuh personnalisées", "Pourquoi créer des règles custom et comment les valider ?",
   "Une règle personnalisée adapte la détection au contexte local lorsque les règles natives ne décrivent pas assez précisément un événement métier ou technique.",
   "Elle s'appuie sur un décodeur, des champs, des conditions, un niveau et parfois une fréquence. Elle doit être testée sur des événements représentatifs et observée pour les faux positifs.",
   "DataForge contient sept règles numérotées 100001 à 100007. wazuh-logtest sert à vérifier le décodage et le déclenchement avant déploiement.",
   "Je teste chaque règle sur un log attendu, puis je vérifie niveau, contexte, bruit et réaction avant de la considérer opérationnelle.",
   "Une règle qui déclenche n'est pas forcément bonne : elle peut être trop large, manquer un contournement ou saturer les analystes."],

  ["SOC", "Suricata", "Quelle différence entre IDS et IPS, et où se situe Suricata ?",
   "Un IDS inspecte le trafic et génère des alertes ; un IPS est placé en ligne et peut bloquer directement les paquets. Suricata peut supporter plusieurs modes, mais son rôle dépend du déploiement réel.",
   "Les règles détectent des signatures ou comportements. Les événements sont écrits en EVE JSON puis transmis à un SIEM pour corrélation et réponse.",
   "DataForge utilise Suricata 6.0.4 avec les règles ET Open en mode IDS sur VM4. EVE JSON alimente Wazuh ; le blocage relève de nftables, Fail2ban ou Active Response.",
   "Dans ma maquette, Suricata détecte et Wazuh corrèle ; je ne le présente pas comme un IPS inline.",
   "Dire 'Suricata bloque les attaques' serait faux pour ce déploiement. Il faut aussi connaître son point d'observation."],

  ["SOC", "Visibilité de Suricata", "Pourquoi une sonde réseau ne voit-elle pas automatiquement tout le trafic ?",
   "Une sonde ne peut analyser que les paquets qui traversent son interface ou qui lui sont copiés par un TAP, un port miroir ou une architecture inline.",
   "Le chiffrement masque aussi le contenu au point d'observation s'il est placé avant déchiffrement. Le placement de la sonde détermine donc sa couverture.",
   "Suricata est installé sur VM4. Sans mirroring généralisé, il voit uniquement le trafic présenté à VM4 et peut manquer certains échanges inter-VM ou le contenu chiffré dans WireGuard.",
   "Je reconnais cet angle mort ; en production je définirais les points de capture, le mirroring, les capacités et la rétention selon les flux critiques.",
   "Le nombre de règles ET Open ne compense jamais une absence de visibilité réseau."],

  ["Windows", "Événements de sécurité Windows", "Que signifient 4624, 4625, 4768 et 4719 ?",
   "Les identifiants d'événement Windows décrivent des actions auditées. Ils deviennent utiles lorsqu'ils sont interprétés avec le compte, le type de connexion, la source et l'heure.",
   "4624 indique une ouverture de session réussie, 4625 un échec, 4768 une demande de TGT Kerberos et 4719 une modification de la politique d'audit.",
   "VM6 et VM7 transmettent ces événements à Wazuh pour détecter essais répétés, comportements d'identité et altérations de la journalisation.",
   "Je corrèle toujours l'ID avec le compte, l'adresse source et le contexte : un 4624 peut être normal et un 4719 peut correspondre à un changement autorisé.",
   "Un identifiant isolé ne prouve ni une attaque ni l'identité réelle de l'auteur."],

  ["SOC", "FIM", "Qu'est-ce que la File Integrity Monitoring et comment traiter une alerte ?",
   "La FIM surveille des fichiers ou répertoires sensibles et signale leur création, modification, suppression ou changement d'attributs.",
   "Elle compare l'état observé à une référence et produit une alerte. L'analyste doit ensuite corréler l'heure, l'utilisateur, le processus, auditd et la gestion de changement.",
   "Wazuh surveille notamment des chemins systèmes sensibles dans DataForge. Une modification de /etc/passwd doit être rapprochée de sudo, auditd et d'une demande autorisée.",
   "La FIM détecte une altération ; elle ne décide pas seule si cette altération est malveillante.",
   "Sans tuning, les mises à jour légitimes créent du bruit. Sans stockage distant, un attaquant privilégié peut aussi tenter d'altérer les preuves locales."],

  ["SOC", "Tests d'incident", "Quels sont les cinq incidents testés et quel est leur intérêt ?",
   "Un test de détection injecte un comportement connu pour vérifier la chaîne complète : génération, collecte, règle, alerte, qualification et éventuellement réponse.",
   "Chaque test doit produire des preuves horodatées et permettre d'identifier les angles morts ou faux positifs.",
   "DataForge teste un brute force, un scan Nmap, un compte backdoor, une escalade ou activité www-data et des handshakes WireGuard suspects.",
   "Ces cinq scénarios valident concrètement la remontée et la corrélation des sources choisies, au-delà d'une simple capture d'écran du dashboard.",
   "Ils ne couvrent ni toutes les techniques MITRE ATT&CK ni tous les contournements possibles."],

  ["SOC", "Résultat de détection à 100 %", "Comment annoncer correctement 100 % de détection ?",
   "Un taux de détection n'a de sens que par rapport à un échantillon, une méthode et une période. Il ne constitue pas une garantie universelle.",
   "Si cinq scénarios sur cinq ont produit l'alerte attendue, le taux est de 100 % pour cette campagne précise. D'autres techniques peuvent rester invisibles.",
   "Les cinq incidents documentés dans DataForge ont été détectés par la chaîne de supervision sécurité.",
   "J'ai obtenu cinq détections sur cinq tests documentés ; je ne prétends pas détecter 100 % des cyberattaques.",
   "Le jury attend cette nuance. Il faut parler aussi des faux négatifs, du tuning, du placement réseau et de la couverture des logs."],

  ["Supervision", "Prometheus", "Que signifie le modèle pull de Prometheus ?",
   "Prometheus est un système de supervision orienté métriques et séries temporelles. Dans son modèle principal, le serveur interroge périodiquement des endpoints HTTP exposant des métriques.",
   "Cette opération, appelée scrape, donne à Prometheus la maîtrise de la fréquence et permet de constater qu'une cible est indisponible si elle ne répond plus.",
   "VM3 exécute Prometheus et interroge les exporters des sept VMs sur le réseau privé WireGuard.",
   "Prometheus collecte activement les métriques CPU, RAM, disque, réseau et disponibilité ; les machines n'envoient pas directement leurs graphiques à Grafana.",
   "Le pull nécessite que les endpoints soient joignables et protégés. Pour les traitements éphémères, un mécanisme complémentaire peut être nécessaire."],

  ["Supervision", "Exporters", "À quoi servent node_exporter et windows_exporter ?",
   "Un exporter traduit les métriques d'un système ou d'une application dans le format que Prometheus peut scrapper.",
   "node_exporter expose les métriques de systèmes Unix/Linux ; windows_exporter expose celles de Windows. Ils n'affichent pas les données eux-mêmes.",
   "Cinq VMs Linux exécutent node_exporter et VM6/VM7 utilisent windows_exporter. Prometheus affiche sept targets UP lorsqu'elles sont toutes accessibles.",
   "Les exporters standardisent la collecte multi-OS ; Grafana visualise ensuite les séries enregistrées par Prometheus.",
   "Un exporter UP ne prouve pas que l'application métier fonctionne. Il faut des sondes de service, healthchecks et métriques applicatives."],

  ["Supervision", "Alertmanager", "Quel est le rôle exact d'Alertmanager ?",
   "Alertmanager reçoit les alertes générées à partir des règles Prometheus et organise leur distribution vers les destinataires.",
   "Il groupe les alertes proches, déduplique les répétitions, applique des inhibitions, route selon des labels et notifie par email, webhook ou autre intégration.",
   "Dans DataForge, il doit transmettre les alertes de disponibilité ou de capacité par mail ou webhook à l'équipe concernée.",
   "Prometheus évalue les conditions ; Alertmanager réduit le bruit et achemine les notifications selon la criticité.",
   "Alertmanager ne corrige pas l'incident et ne remplace pas un runbook, une astreinte, un acquittement et une escalade."],

  ["Supervision", "Blackbox Exporter", "Pourquoi une sonde Blackbox complète-t-elle node_exporter ?",
   "Blackbox Exporter réalise des sondes actives HTTP, TCP, ICMP ou TLS depuis le point de vue d'un client ou d'un réseau donné.",
   "Il vérifie la résolution, la connexion, le code HTTP, le certificat ou le temps de réponse, tandis qu'un exporter système observe surtout l'état interne de la machine.",
   "DataForge peut tester l'accès HTTPS à l'application, les ports critiques et l'expiration TLS même si CPU et processus semblent normaux.",
   "Une VM peut être UP avec une application en erreur 500 ; Blackbox mesure le service réellement perçu.",
   "Une sonde unique ne représente pas tous les sites utilisateurs. En production, il faut choisir plusieurs points de mesure et des SLO."],

  ["Supervision", "Prometheus et Wazuh", "Pourquoi ces deux plateformes ne font-elles pas doublon ?",
   "Prometheus est centré sur les métriques numériques de santé et de performance ; Wazuh est centré sur les événements, journaux, intégrité et détection de sécurité.",
   "Les métriques indiquent une saturation ou une indisponibilité. Les logs expliquent souvent quelle action ou identité a provoqué le symptôme.",
   "VM3 héberge Prometheus/Grafana/Alertmanager ; VM4 héberge Wazuh et les sources SOC. Les deux vues se complètent lors d'une investigation.",
   "Prometheus répond surtout à 'le service fonctionne-t-il correctement ?' et Wazuh à 'quel événement de sécurité s'est produit et avec quel contexte ?'.",
   "Il existe des recouvrements, mais fusionner les rôles sans stratégie de rétention et de corrélation peut augmenter le bruit et le coût."],

  ["PCA / PRA", "RTO, RPO et MTTR", "Quelle différence entre RTO, RPO et MTTR ?",
   "Le RTO est la durée maximale visée avant rétablissement d'un service. Le RPO est la quantité maximale de données que l'organisation accepte de perdre. Le MTTR mesure le temps moyen réellement nécessaire pour rétablir.",
   "Le RPO détermine la fréquence des sauvegardes ; le RTO influence l'automatisation, la redondance, les procédures et les ressources de reprise.",
   "DataForge vise un RTO inférieur à 4 heures, un RPO inférieur à 24 heures et un MTTR inférieur à 2 heures.",
   "Une sauvegarde quotidienne peut soutenir un RPO de 24 heures, mais le RTO de 4 heures doit être prouvé par un exercice chronométré de restauration.",
   "Ne pas confondre objectif et résultat. Un chiffre écrit dans le PRA n'est pas une mesure obtenue tant que le test complet n'a pas été exécuté."],

  ["PCA / PRA", "Preuve d'une sauvegarde", "Pourquoi la présence d'un fichier de backup est-elle insuffisante ?",
   "Une sauvegarde utile doit être complète, intègre, lisible, protégée et restaurable dans le délai attendu.",
   "Le test consiste à restaurer dans un environnement isolé, vérifier les objets et données, relancer la fonction, contrôler les droits puis mesurer la durée.",
   "DataForge prévoit des restaurations PostgreSQL, LDAP et AD, avec validation des données et du service après reprise.",
   "Je considère la restauration comme la véritable preuve ; le cron et le fichier ne démontrent que l'exécution apparente de la copie.",
   "Il faut aussi tester les clés de chiffrement, les dépendances, les versions, les comptes et la documentation utilisée par une autre personne."],

  ["PCA / PRA", "Sauvegarde OpenLDAP", "Comment sauvegarder et restaurer correctement OpenLDAP ?",
   "slapcat exporte la base OpenLDAP dans un fichier LDIF au niveau local, indépendamment d'une requête LDAP classique. Le LDIF décrit les entrées de l'annuaire.",
   "Pour restaurer, on arrête le service si nécessaire, réinjecte avec l'outil adapté, rétablit propriétaires et permissions puis valide les recherches et authentifications.",
   "VM5 produit un export LDIF quotidien avec une rétention de trente jours et une copie cloud prévue.",
   "La restauration n'est validée qu'après contrôle des utilisateurs, groupes, schémas, ACL, ppolicy et authentifications SSSD.",
   "Un LDIF peut ne pas couvrir à lui seul tous les fichiers de configuration, certificats et secrets nécessaires au service."],

  ["PCA / PRA", "Sauvegarde Active Directory", "Pourquoi System State est-il plus important que LDIFDE seul ?",
   "Le System State d'un contrôleur de domaine sauvegarde les composants système nécessaires à AD DS, notamment la base d'annuaire et des éléments liés au démarrage et à la configuration.",
   "LDIFDE exporte des objets LDAP mais ne reconstitue pas seul l'intégralité d'un contrôleur de domaine et de son contexte système.",
   "VM6 utilise Windows Server Backup pour le System State, complété par LDIFDE, avec une rétention de quatorze jours sur un volume dédié.",
   "J'utilise System State pour la reprise du DC et LDIFDE comme export complémentaire d'objets, puis je teste DNS, Kerberos, GPO et la jointure.",
   "La restauration AD doit respecter le scénario autoritaire ou non autoritaire et être testée avec la réplication prévue en production."],

  ["PCA / PRA", "Stratégie 3-2-1", "Que signifie 3-2-1 et pourquoi DataForge ne l'atteint-il que partiellement ?",
   "La règle 3-2-1 recommande trois copies des données, sur deux types de supports, dont une copie hors site. Une variante moderne ajoute une copie immuable ou hors ligne et des tests.",
   "Elle réduit le risque qu'une panne, une erreur ou un ransomware détruise simultanément la production et toutes les sauvegardes.",
   "DataForge combine copies locales et réplication cloud de certains éléments critiques, avec des rétentions définies.",
   "Je parle d'une approche 3-2-1, car l'externalisation et l'immutabilité ne couvrent pas encore uniformément PostgreSQL, LDAP, AD et les configurations.",
   "Une copie dans un autre dossier de la même VM ne constitue ni un second support ni une protection contre la compromission de l'hôte."],

  ["Dossier professionnel", "ModSecurity et OWASP CRS", "Dans quel projet ModSecurity a-t-il réellement été déployé ?",
   "ModSecurity est un moteur de Web Application Firewall. L'OWASP Core Rule Set fournit des règles génériques contre des familles d'attaques web telles que injections, traversées ou accès à des fichiers sensibles.",
   "Une mise en service prudente commence en detection-only pour observer les faux positifs, puis passe en blocage après ajustement.",
   "Le DP documente ModSecurity et OWASP CRS 4.25.0 sur le serveur Plesk de NetStrategy. Ce déploiement ne doit pas être attribué à VM2 sans preuve dans le PFE.",
   "ModSecurity constitue une preuve professionnelle NetStrategy ; dans DataForge, la détection réseau repose notamment sur Suricata et Wazuh.",
   "Le jury teste ici ta capacité à séparer PFE et DP. Un WAF ne remplace pas non plus la correction du code applicatif."],

  ["Dossier professionnel", "Résultats NetStrategy", "Quels chiffres démontrent une amélioration mesurée chez NetStrategy ?",
   "Une preuve professionnelle solide associe un état initial, une action personnelle, un résultat mesuré et idéalement une vérification dans le temps.",
   "Les chiffres doivent être contextualisés : outil, date, périmètre et limite. Ils ne remplacent pas l'explication de la méthode.",
   "Le DP indique Lynis 67 puis 77 et 75 après deux mois, 266 Go libérés, neuf conteneurs remis en état et neuf CVE kernel corrigées à chaud.",
   "Ces mesures montrent que le hardening a amélioré la sécurité et l'exploitation, puis qu'une vérification de persistance a été réalisée deux mois plus tard.",
   "Le léger passage de 77 à 75 doit être expliqué honnêtement par l'évolution du système ou des contrôles, pas masqué."],

  ["Dossier professionnel", "Incident /.env", "Comment présenter le traitement complet de l'incident .env ?",
   "Le traitement d'incident suit une chaîne : détection, qualification, confinement, éradication, restauration, validation, communication et retour d'expérience.",
   "Une tentative d'accès à .env est grave car ce fichier peut contenir identifiants BDD, clés d'API et autres secrets permettant une compromission plus large.",
   "Parmi treize événements ModSecurity en detection-only, une vraie tentative LFI visait /.env. Le WAF est passé en blocage, Nginx a protégé quinze domaines, un .env.backup exposé a été déplacé, puis des tests 403/404 et un contrôle à deux mois ont validé la remédiation.",
   "Je ne me suis pas arrêté à l'alerte : j'ai qualifié le risque, supprimé l'exposition, généralisé la règle, documenté un runbook et vérifié la persistance.",
   "Évite de dire que les treize événements étaient treize attaques : douze étaient des faux positifs ou événements non malveillants."],

  ["Posture jury", "Structure d'une réponse", "Quelle structure utiliser pour répondre clairement au jury ?",
   "Une réponse professionnelle commence par la conclusion, puis fournit la justification et les preuves avant d'exposer les limites et les suites.",
   "La structure recommandée est : réponse directe, définition ou mécanisme, application au projet, preuve, limite, amélioration de production.",
   "Pour chaque outil DataForge, cite un flux, une configuration, un test, un résultat ou une page du dossier, puis distingue clairement maquette et production.",
   "Ma réponse est oui ou non d'abord ; j'explique ensuite le choix, la preuve et la limite avant de proposer l'industrialisation.",
   "Commencer par cinq minutes de contexte sans répondre donne l'impression d'éviter la question. Inventer pour combler un doute est beaucoup plus risqué que le reconnaître."],

  ["RNCP", "CP4 — infrastructures virtualisées", "Quelle est la limite de la preuve CP4 et comment la défendre ?",
   "CP4 porte l'administration et la sécurisation d'infrastructures virtualisées : ressources, réseaux, stockage, disponibilité, sauvegarde, exploitation et sécurité de l'hyperviseur.",
   "Une collection de VMs prouve la virtualisation de base, mais la profondeur augmente avec cluster, HA, migration, stockage partagé, templates et supervision.",
   "DataForge utilise VirtualBox et Oracle Cloud sans cluster complet. Le DP apporte une preuve complémentaire Proxmox avec trois VMs Debian, réseau privé et provisioning automatisé.",
   "Je couvre CP4 par la conception et l'exploitation des VMs, tout en reconnaissant l'absence de HA ; mon expérience Proxmox complète la preuve d'administration virtualisée.",
   "Ne prétends pas avoir démontré migration à chaud ou stockage distribué si ces fonctions n'ont pas été testées."],

  ["RNCP", "CP6 — mise en production", "Pourquoi CP6 ne se résume-t-elle pas à installer une solution ?",
   "La mise en production est un processus contrôlé qui prépare, planifie, déploie, valide et documente un changement tout en protégeant les niveaux de service.",
   "Elle inclut prérequis, sauvegarde, fenêtre, responsabilités, tests, supervision, retour arrière, transfert de compétences et mise à jour documentaire.",
   "DataForge apporte plans, scripts, sauvegardes, tests, supervision et PRA. Le DP prouve une méthode de changement sûre sur SSH, Plesk et l'infrastructure Proxmox.",
   "Je défends CP6 par la maîtrise du changement : validation avant/après, continuité, rollback, documentation et preuve de persistance.",
   "Dire 'j'ai installé et ça marche' ne prouve ni le risque maîtrisé, ni le retour arrière, ni le transfert aux exploitants."],

  ["Production", "Budget de 34 000 € par an", "Comment défendre ce coût sans le présenter comme un prix exact ?",
   "Un chiffrage d'infrastructure est une estimation fondée sur des hypothèses de capacité, disponibilité, support, licences, stockage, réseau et charge humaine.",
   "Il faut séparer investissements et exploitation, présenter une fourchette, documenter les quantités et montrer comment le coût évolue avec les SLA.",
   "Les 34 000 € annuels de DataForge agrègent cloud ou matériel, support, sauvegarde, collecte de logs, réseau, maintenance et temps d'exploitation selon la cible proposée.",
   "Je présente 34 000 € comme un ordre de grandeur lié à des hypothèses explicites, à recalculer après dimensionnement et consultation des fournisseurs.",
   "Un chiffre isolé est fragile. Les coûts cloud, salariaux et de support varient ; il faut donner la date, le périmètre et ce qui est exclu."],

  ["Épreuve", "Durée de la présentation", "Comment organiser les 40 minutes sans réciter le dossier ?",
   "La présentation de projet doit synthétiser les décisions, preuves et compétences ; elle n'est pas une lecture des pages du PFE.",
   "Un minutage répartit le temps entre contexte, besoin, architecture, mise en œuvre, sécurité, IAM, supervision/SOC, risques, tests, limites et conclusion.",
   "Le pitch DataForge prévoit 0–5 contexte, 5–13 architecture, 13–23 sécurité/IAM, 23–31 supervision/SOC, 31–36 EBIOS et 36–40 tests, limites, RNCP et conclusion.",
   "Je vise 38 à 40 minutes avec des transitions et des preuves, en français conformément aux modalités confirmées par le centre.",
   "L'oral blanc a duré 25 minutes : accélérer davantage serait contre-productif. Il faut développer les choix et leurs limites, pas ajouter du remplissage."],

  ["Posture", "Retour de l'oral blanc", "Quels comportements faut-il corriger avant le jury ?",
   "La posture influence la compréhension : volume, rythme, pauses, regard, intonation et gestes doivent soutenir l'argumentation technique.",
   "Une pause silencieuse est plus professionnelle qu'un tic de langage. Les tableaux détaillés peuvent être imprimés pour préserver la lisibilité des slides.",
   "Le retour indique une bonne vulgarisation et une entreprise bien présentée, mais seulement 25 minutes, une voix à renforcer, plus d'intonation, davantage de forces/faiblesses et la suppression de 'tac'.",
   "Je ralentis sur les décisions importantes, je regarde le jury, je parle plus fort et j'utilise une pause lorsque je cherche ma transition.",
   "Apprendre tout mot pour mot peut rendre la voix monotone. Il vaut mieux mémoriser le fil, les chiffres et les preuves."],

  ["Posture jury", "Répondre quand on ne sait pas", "Que faire face à une question dont tu ignores la réponse ?",
   "Une réponse honnête peut démontrer une méthode professionnelle : borner ce que l'on sait, ne pas inventer, expliquer le risque et décrire comment vérifier.",
   "On peut reformuler la question, distinguer hypothèse et fait, citer les sources ou commandes à consulter, puis proposer une décision prudente en attendant la preuve.",
   "Pour DataForge, tu peux dire : ce point n'a pas été testé dans la maquette ; je vérifierais la configuration, les logs et la documentation avant changement, puis je validerais en environnement isolé.",
   "Je ne peux pas l'affirmer avec les preuves actuelles ; voici ce que je contrôlerais et comment je sécuriserais la décision.",
   "Évite le simple 'je ne sais pas' sans méthode, mais surtout n'invente jamais un déploiement, une version, un test ou un résultat absent des dossiers."]
].map(([category, term, question, definition, mechanism, dataforge, oral, trap]) => ({category, term, question, definition, mechanism, dataforge, oral, trap}));

const oralQuestions = [
  ["Architecture","Présentez DataForge et votre rôle en 90 secondes.","Entreprise industrielle fictive de 120 personnes sur trois sites. J’ai conçu et déployé une maquette de sept VMs pour sécuriser accès, identités, données et exploitation. Deux VMs sont prévues sur Oracle Cloud, cinq sous VirtualBox, reliées par WireGuard. L’identité est hybride OpenLDAP/AD et la défense combine durcissement, supervision, SIEM et PRA. Je distingue la cible de production des preuves du lab."],
  ["Architecture","Expliquez un flux administrateur vers VM2.","WireGuard vers VM1, identité et TOTP au bastion, puis flux SSH explicitement autorisé par nftables vers VM2. VM2 n’est pas exposée. Les authentifications et actions remontent à Wazuh."],
  ["Architecture","Que se passe-t-il si VM1 tombe ?","Perte du hub et du point d’entrée. Certains services locaux peuvent tourner, mais les accès inter-sites et l’administration sont coupés. Production : deux gateways, bascule, synchronisation et tests."],
  ["Réseau","Pourquoi pas de VLAN physiques ?","Pas de switch administrable dans le lab. WireGuard, nftables et Docker démontrent la segmentation. Production : VLAN/VRF, NGFW, inter-zones et séparation IT/OT."],
  ["Choix","Pourquoi VirtualBox ?","Portable et reproductible pour le lab. Proxmox/VMware en production pour cluster, HA, migration, stockage et administration. Mon DP apporte Proxmox."],
  ["Zero Trust","Prouvez les 5 principes.","Clés/TOTP/LDAP/Kerberos ; RBAC/nologin ; WireGuard/nftables/Docker ; FIM/auditd/Suricata ; Wazuh/logs. Limites : MFA et autorisation dynamique non généralisés."],
  ["EBIOS","Valeur, support, événement, scénario ?","Valeur : donnée/continuité. Support : PostgreSQL/AD/LDAP. Événement : fuite ou annuaire compromis. Scénario : chemin, par exemple phishing VM7 vers VM6."],
  ["EBIOS","Pourquoi 3 critiques ?","Fuite affecte confiance/conformité ; AD donne contrôle Windows/GPO ; LDAP ouvre les hôtes SSSD. Impacts systémiques."],
  ["EBIOS","Pourquoi accepter 5 modérés ?","Acceptation bornée au lab après traitement. Facteur humain et contrôles non industrialisés. Production : responsable, plan, échéance, MFA, CIS, EDR, IPS et réévaluation."],
  ["Identité","Pourquoi 2 annuaires ?","LDAP léger pour Linux/SSSD ; AD pour DNS/Kerberos/GPO Windows. FreeIPA plus intégré mais plus complexe. Contrepartie : gouvernance de deux sources."],
  ["Identité","Sont-ils synchronisés ?","Je ne revendique pas de synchronisation automatique. Production : source maîtresse, provisioning, Joiner-Mover-Leaver, recertification."],
  ["Identité","Pourquoi MFA pas partout ?","Priorité au bastion VM1. Limite assumée. Production : MFA privilégié, accès distants, consoles critiques et récupération contrôlée."],
  ["SSH","Changer SSH sans couper l’accès ?","Seconde session, backup, sshd -t, reload, nouvelle connexion, logs, fermeture ensuite. Méthode prouvée dans le DP."],
  ["Code","Expliquez et critiquez le backup PostgreSQL.","pg_dump dans df-postgres, gzip, date, purge 30 jours. Ajouter pipefail, code retour, intégrité, permissions, chiffrement, espace, hors site et test automatique de restauration."],
  ["Docker","BDD non exposée suffit ?","Non : comptes distincts, secrets, droits, patching, chiffrement backups, réseau backend, non-root, capabilities/seccomp et logs."],
  ["Audit","Lynis 72 = 72 % sécurisé ?","Non, indice relatif. À croiser avec Nmap, Nikto, vulnérabilités, Wazuh et tests."],
  ["SOC","Chaîne Suricata vers traitement ?","ET Open → EVE JSON → Wazuh → corrélation hôte/audit → qualification → confinement nftables/Fail2ban/Active Response. Suricata reste IDS."],
  ["SOC","100 % de détection crédible ?","Oui seulement pour les 5 incidents testés. Pas une couverture universelle ; mentionner faux négatifs, tuning et angle mort réseau."],
  ["SOC","7 agents Wazuh ?","Manager local VM4 + 6 distants = 7 machines couvertes."],
  ["SOC","Alerte FIM /etc/passwd ?","Corréler heure, utilisateur, processus, diff, auditd, sudo et changement. Si illégitime : contenir, préserver, restaurer, chercher persistance, RETEX."],
  ["Supervision","Prometheus et Wazuh doublon ?","Non : métriques santé/capacité contre événements sécurité/traçabilité. Grafana, Alertmanager et Blackbox complètent."],
  ["Supervision","VM UP, application KO ?","node_exporter peut rester UP. Probe Blackbox, healthcheck, métriques métier, logs application/Nginx/Docker/Wazuh."],
  ["PRA","Prouver RTO < 4 h ?","Exercice chronométré de reconstruction/restauration/validation. Scripts et docs rendent plausible ; test complet confirme."],
  ["PRA","Pourquoi fichier backup insuffisant ?","Peut être vide, corrompu, incomplet ou sans clé. Restaurer isolé, vérifier objets/données/fonction et mesurer."],
  ["Production","Défendre 34 000 €/an ?","Estimation : cloud/matériel, support, sauvegarde, logs, réseau, licences, maintenance, humain. Donner charge, CAPEX/OPEX et fourchette."],
  ["Production","5 priorités ?","HA VM1/annuaires ; IT/OT ; MFA/secrets ; backups immuables/testés ; automatisation/conformité/rollback ; puis EDR/IPS selon risque."],
  ["DP","Hardening NetStrategy chiffré ?","20 risques, 11 docs, SSH/Docker/swap/Livepatch. Lynis 67→77→75, 266 Go, 9 conteneurs, 9 CVE sans downtime."],
  ["DP","Incident /.env ?","Vraie LFI parmi 13 événements, secrets qualifiés, WAF bloquant, Nginx 15 domaines, backup déplacé, tests 403/404, runbook, contrôle 2 mois."],
  ["RNCP","CP1–CP10 au même niveau ?","Toutes représentées, profondeur variable. CP3/7/8/9/10 fortes. CP4/6 à défendre avec Proxmox DP et processus de changement/rollback."],
  ["Posture","Correction oral blanc ?","Base claire mais 25 min. Ralentir, détailler forces/faiblesses, pages/CP, parler plus fort, varier l’intonation, gestes sobres, pause au lieu de “tac”."]
];

window.DATAFORGE_CONTENT = { sheets, qcm, flashcards, oralQuestions };
